source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 35400729-6c24-49d5-a72b-230dc71eb985
      metricId: 0b1e4943-b176-433b-8af6-b908f31f5129
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 400
      incident:  
    - entityId: 35400729-6c24-49d5-a72b-230dc71eb985
      metricId: dbc71420-dcf1-4458-a806-ff84e76f9bf8
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: 35400729-6c24-49d5-a72b-230dc71eb985
      metricId: 4c238762-dfee-4f5e-8cb3-2d0901886aac
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: b66cd271-3163-41d7-8076-6d7390e73509
      metricId: 204f4ead-c75f-4b45-a566-2b13bec79bac
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 0
      max: 200
      incident:  
    - entityId: ab098164-6bff-48b1-a71b-4d6a788680d8
      metricId: ecf9dee9-867d-4714-b19a-78a5c315b601
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
    - entityId: c06f7f45-4931-4793-9b8c-0e988c0e43ba
      metricId: def5280d-f287-4adb-9b18-75d5d9f7c96a
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 35400729-6c24-49d5-a72b-230dc71eb985
      metricId: 641e1b6d-a712-4af5-8072-3f91e1123e52
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: 35400729-6c24-49d5-a72b-230dc71eb985
      metricId: 0909b300-5608-4796-b18a-2e0721f80b2c
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 300
      incident:  
