source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 86d25853-401b-4fb6-92a1-019142255a6c
      metricId: a4376b54-b3db-45d8-84e4-8dfb8fdf2959
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Performance
      legendName: Average
      min: 0
      max: 950
    - entityId: 85cd53cc-b588-476f-8fb5-2683b2fbeaf6
      metricId: b19020a3-9515-48dd-b020-a11946c44c6d
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: TPM
      legendName: TPM
      min: 0
      max: 150
    - entityId: 60943319-f82f-4215-87cd-96b5509cdd13
      metricId: f6b1e762-9895-406d-8ea3-caa1ad1d06f8
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Error
      legendName: Failure
      min: 0
      max: 2000
    - entityId: fdcbf74a-ab3f-40d1-abce-21527e4daa67
      metricId: 5d4167cd-ee31-4510-8a04-bb9b69da9f1e
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Availability
      legendName: Availability
      min: 94
      max: 100
      incident: sev2
    - entityId: 86d25853-401b-4fb6-92a1-019142255a6c
      metricId: efcdac6c-7115-402c-98d0-8e831a8ef5b4
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Performance
      legendName: p99
      min: 0
      max: 3500
    - entityId: 86d25853-401b-4fb6-92a1-019142255a6c
      metricId: 801b8ebc-7fe3-49b9-9595-973a7ac43661
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 4000
    - entityId: 86d25853-401b-4fb6-92a1-019142255a6c
      metricId: 417c0cd1-e536-45ef-8129-5ae53a944fe2
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 4000
    - entityId: 86d25853-401b-4fb6-92a1-019142255a6c
      metricId: 565e846f-0b5f-4230-81e1-36daa26bd1cb
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: DCP
      graphName: Performance
      legendName: p95
      min: 0
      max: 2000
