source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 7c601e21-f6ff-4187-bd32-b26ae325933a
      metricId: 2bde561a-69b4-4800-8595-b97491180f83
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Web Login Customer Experience
      graphName: Web Login Customer Experience
      legendName: MFA POA
      min: 99.9
      max: 100
      incident: sev2
    - entityId: c015da83-813c-4fb3-9ea6-580d499c0428
      metricId: f72ffcb7-5369-4649-a869-f4831e454d3f
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Web Login Customer Experience
      graphName: Web Login Customer Experience
      legendName: CBIS
      min: 99.9
      max: 100
      incident: sev2
    - entityId: 132fdd8e-4583-4ed5-a7ba-29b13d7c380b
      metricId: 8c3f53f6-8b83-4f28-a7e5-34f97b0c7b5a
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Web Login Customer Experience
      graphName: Web Login Customer Experience
      legendName: MFA POD
      min: 99.9
      max: 100
      incident: sev2
