source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: f083165b-43f6-4393-bffd-16d8cc759748
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: appwd947
      incident:  
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: 9983e4d1-a969-4dae-b0dc-17927b8fd4b0
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: agpwd689
      incident:  
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: e5e06672-8bce-4fd0-842a-ca00aac08cb1
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: appwd947
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: d9812453-36d8-4949-9314-bf6fe01b3826
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: agpwd689
      incident:  
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: b298226c-231f-4fab-8885-fdab6f53b81c
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: agpwd661
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: 9f9a5195-9927-4e37-94b7-eb5310568a73
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: agpwd661
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: cb185ead-ee53-4267-9cb7-769a7f211632
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: agpwd675
      incident:  
    - entityId: d29bce11-9ff1-4bd6-a1f1-1ea986a3ee76
      metricId: dbee000b-21bf-40d0-a5fa-659dbf1a5bec
      parentEntityId: b90c97f8-267c-4b96-8061-8e90318d4a0d
      containerName: Biometric Login Availability Dependencies
      graphName: DB2 Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: 91ad098e-394c-4246-b02a-536c2c083a4b
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: agpwd675
      min: 0
      max: 12
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: bcecbeb3-a048-4e4c-8b69-a6f672df8817
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: agpwd675
      incident:  
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: 80f9c09a-e33a-4ddb-9d0b-b8a5c20e80e4
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: agpwd675
      incident:  
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: 6ba97fe4-89a7-4174-ab3f-d38641b58365
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: appwd931
      min: 0
      max: 3
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: 2b25fbee-8aa6-4020-91ff-b7f5ecf93006
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: agpwd689
      incident:  
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: fe529edf-439e-4922-b8ea-7ea47c0e29ad
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: agpwd661
      incident:  
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: ee70b2e5-1dac-4ccc-8b15-c95ef6a0604a
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: appwd931
      min: 0
      max: 150
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: fd9c8ccf-f817-4378-9c30-255386d5a925
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: appwd947
      incident:  
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: 82d2dac7-dc69-488c-987c-eaf8d926a6c3
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: appwd947
      incident:  
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: 13fa316d-9d21-44cd-8c86-d4d96b73cc04
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: appwd931
      min: 0
      max: 15
      incident:  
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: 3136f6b4-b9ce-4037-b7da-24a153724443
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: appwd963
      incident:  
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: bce7f76a-1448-47b9-b085-a2897fe304a5
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: agpwd661
      min: 0
      max: 12
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: 4fe36692-bedc-42a2-b060-5b9fc406043f
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: appwd963
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: 2a5d5539-5fb8-4229-a872-778bd61170b3
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: appwd931
      min: 0
      max: 50
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: 4dfe66e8-08a4-441e-83bb-d703884832e8
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: agpwd675
      incident:  
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: e23d5a07-afbe-4bb5-8f97-443324040c13
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: agpwd661
      incident:  
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: 4ffeeb83-5e26-40e2-ba1f-a33be549eb67
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: agpwd689
      min: 0
      max: 12
      incident:  
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: 5b73bfb8-4de5-4f1a-b167-441d0dac1609
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: agpwd675
      incident:  
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: 5121ba2b-5a3f-4dea-894a-b28ca1d287aa
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: appwd963
      min: 0
      max: 12
      incident:  
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: a4f3eec8-80ee-4531-bb69-e63ab7c0e50d
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: appwd963
      incident:  
    - entityId: 1ea05cc6-3345-4bb2-a943-887335da5087
      metricId: 32178587-31e6-4c53-8405-438773c9cd69
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Deadlock
      legendName: appwd931
      min: 0
      max: 3
    - entityId: 24de62a4-7fcd-446b-af88-82e10099d213
      metricId: 3ef993ed-c415-48b9-add1-71665247f2c9
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: TPM
      legendName: appwd963
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: c51b4ac8-48de-4264-8e41-866bff5a319e
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: appwd931
      min: 0
      max: 300
      incident:  
    - entityId: 7db01940-2b8e-4836-a5ec-fcb8091ea155
      metricId: 28b07c8e-83de-4d36-a2b2-0b87abf8b0e7
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Lock Timeout
      legendName: agpwd689
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: 53edc1ed-78a8-43c4-91a4-ea04c28cfd5e
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: appwd947
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: fc565838-bfa1-46b2-b3c3-88a5e1947f3b
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: appwd963
      incident:  
    - entityId: 213612a0-26a2-486d-b6ba-5209e075178b
      metricId: ac169886-91e6-4d08-be53-e7685aa2c750
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Wait Time
      legendName: agpwd689
      incident:  
    - entityId: edeb3bce-0f09-4513-9760-ebe5998c8216
      metricId: 75667825-9ee8-490e-a469-a7950b44b5d4
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: CPU
      legendName: appwd947
      min: 0
      max: 12
      incident:  
    - entityId: 66cc5fd5-8369-411d-bb2d-e4987b802ce9
      metricId: eb5911f0-41d8-4e11-9a8e-87e55612c03a
      parentEntityId: db34c9a4-f823-4ae6-89d4-c6fdde117677
      containerName: DB2 Availability Golden Signals
      graphName: Connection
      legendName: agpwd661
      incident:  
