source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 9946542e-ea61-42f2-90fe-a64081ef65b2
      metricId: 2173df73-dd62-4d78-ab94-ee743fcbfc87
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Availability
      legendName: Availability
      min: 96
      max: 100
      incident: sev2
    - entityId: 95de5af2-9ecd-4ab8-9a13-75f52f755b5e
      metricId: 22d32b60-e645-4fd5-8be0-c26f169a3fea
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99
      min: 0
      max: 1200
      incident:  
    - entityId: 95de5af2-9ecd-4ab8-9a13-75f52f755b5e
      metricId: 13dd0043-c0ea-46f8-af76-5f9ca0b9861d
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: 95de5af2-9ecd-4ab8-9a13-75f52f755b5e
      metricId: 7bf0d2d0-1fb0-4728-853f-0dd0e1e491f5
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p95
      min: 0
      max: 750
      incident:  
    - entityId: fe59c6f7-93e8-4840-8c28-fd1d5e2d4cba
      metricId: f13c2931-6119-4046-ae68-68f7b3962b9b
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Error
      legendName: Exception
      min: 0
      max: 20
      incident:  
    - entityId: 95de5af2-9ecd-4ab8-9a13-75f52f755b5e
      metricId: 44cd4603-e882-41f0-86bb-b4287ae1f0e5
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2000
      incident:  
    - entityId: 95de5af2-9ecd-4ab8-9a13-75f52f755b5e
      metricId: 46c1c54c-2f8f-4f17-b6bc-08a8783a181a
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: Average
      min: 0
      max: 300
      incident:  
    - entityId: fe59c6f7-93e8-4840-8c28-fd1d5e2d4cba
      metricId: 58fc8740-33b2-43c7-8015-f5ef3ea1dac4
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Error
      legendName: Failure
      min: 0
      max: 10
      incident:  
    - entityId: 7265c1d3-d157-4877-9e80-38329e96d11c
      metricId: 16c5c979-a7bd-4b29-b4fd-afe9371ed531
      parentEntityId: d4e8df06-6d72-4675-8f34-2aad62b04f23
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: TPM
      legendName: TPM
      min: 0
      max: 750
      incident:  
