source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 2b2aea5b-7c0d-47b8-9054-59216381442c
      metricId: 3fa34b71-f021-4723-bc46-253ad540d712
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Performance
      legendName: p99
      incident:  
    - entityId: 2b2aea5b-7c0d-47b8-9054-59216381442c
      metricId: 4dbf66d0-5e71-4306-904a-579459883bbf
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Performance
      legendName: p95
      incident:  
    - entityId: 2b2aea5b-7c0d-47b8-9054-59216381442c
      metricId: ba55a3f5-eba1-4109-a34e-164b6801757c
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.9
    - entityId: 2b2aea5b-7c0d-47b8-9054-59216381442c
      metricId: e938800f-f9ff-4353-a012-c36e9cf67714
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.99
      incident:  
    - entityId: 18d6473a-4be8-492d-9054-80b44f17efc4
      metricId: f80d937a-ad29-4c34-9ed2-f27145e0a881
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 500
      incident:  
    - entityId: 1b8e13f5-c65e-41be-8d62-50ed1bfb3665
      metricId: dccd39b7-fe97-4ad4-a97b-1dee2496c621
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Error
      legendName: Failure
      incident:  
    - entityId: 926c51ab-1cbd-4fba-a4bb-c74b6394ba1d
      metricId: e765be96-dd10-4f16-9134-a4320a7ac1f2
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Availability
      legendName: Availability
      incident:  
    - entityId: 2b2aea5b-7c0d-47b8-9054-59216381442c
      metricId: 295a8c93-7b44-4b75-a7da-644fc08ea70f
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Lockout DB
      graphName: Performance
      legendName: Average
      incident:  
