source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: aa791aa4-c346-4b95-a2fb-c2eaaabec4e2
      metricId: bdb09181-a8d7-4df0-ab9d-2bdb71814b64
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Error
      legendName: Exception
      min: 0
      max: 40
      incident:  
    - entityId: d7ebd695-c5d4-493c-b5eb-e0c65a6808be
      metricId: cc83726f-1cf9-4065-a043-be68712982b2
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: TPM
      legendName: TPM
      min: 0
      max: 500
      incident:  
    - entityId: 4c432887-b013-466d-817c-647364843649
      metricId: 3c394117-c8c2-4efc-b9a9-883709390685
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: c86110e6-af17-4c45-b472-933bbf39b3ef
      metricId: 924060f6-6d1f-4bed-9803-f1db1b15eb7c
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1000
    - entityId: c86110e6-af17-4c45-b472-933bbf39b3ef
      metricId: 769a4cd1-574e-4ce8-8aa6-205188e48614
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Performance
      legendName: Average
      min: 0
      max: 400
      incident:  
    - entityId: aa791aa4-c346-4b95-a2fb-c2eaaabec4e2
      metricId: 73df9b6d-713d-49cd-ae67-9dd8c9256479
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: c86110e6-af17-4c45-b472-933bbf39b3ef
      metricId: 6c88115d-f089-4498-91df-cc33e02f2dfb
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: c86110e6-af17-4c45-b472-933bbf39b3ef
      metricId: 843ec1a3-35f8-416e-a6aa-b3beb900ddb2
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Performance
      legendName: p95
      min: 0
      max: 500
      incident:  
    - entityId: c86110e6-af17-4c45-b472-933bbf39b3ef
      metricId: 27e1b927-75e3-4f09-960e-8667d15aa44b
      parentEntityId: 8256e444-f84c-43cc-8777-ea495cdeddaf
      containerName: OTP AuthN - OTP Delivery
      graphName: Performance
      legendName: p99
      min: 0
      max: 1000
      incident:  
