source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 27be1829-d259-430f-bb2b-fab23681e0d5
      metricId: 97864b39-34f1-43b8-818b-a4a81885e02f
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 0bf93e3c-45e5-423f-a9c9-138b9f26d47f
      metricId: 781d9d05-a85e-4b66-963c-d60d690fb3a7
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Performance
      legendName: Average
      min: 0
      max: 200
      incident:  
    - entityId: 1191b72e-f0b8-41b1-8f1b-885a6797b86e
      metricId: 233b7640-0030-43e5-8ed7-b5f849684dab
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: TPM
      legendName: TPM
      min: 0
      max: 700
      incident:  
    - entityId: 0bf93e3c-45e5-423f-a9c9-138b9f26d47f
      metricId: ed84eafa-8870-41dd-b065-d97618c48847
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1700
      incident:  
    - entityId: 7181a2bd-37ab-45f6-889d-fe63074f8e65
      metricId: 8146d26e-a6de-43f3-8377-8878fe571505
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Error
      legendName: Exception
      min: 0
      incident:  
    - entityId: 7181a2bd-37ab-45f6-889d-fe63074f8e65
      metricId: b1522c1e-6e7f-46ae-9af9-d52b30eefd09
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: 0bf93e3c-45e5-423f-a9c9-138b9f26d47f
      metricId: 15a1d538-9998-4133-8586-1829b2553653
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: 0bf93e3c-45e5-423f-a9c9-138b9f26d47f
      metricId: 5c4666ba-26ad-44e8-93ba-24e2cbd68e03
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: 0bf93e3c-45e5-423f-a9c9-138b9f26d47f
      metricId: 94e4bf57-38e0-4fae-a08d-03a1289dfcaf
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: Push AuthN - Get Eligible PUSH channels
      graphName: Performance
      legendName: p95
      min: 0
      max: 800
      incident:  
