source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: fb5a6124-143a-4762-9294-538a78a98bd8
      metricId: 52ed3281-33e3-463c-89bf-afc5b33274e7
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 500
      incident:  
    - entityId: fb5a6124-143a-4762-9294-538a78a98bd8
      metricId: ca3ea9cc-76ca-4d0b-8038-f23da19ff836
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Performance
      legendName: Average
      min: 0
      max: 80
      incident:  
    - entityId: fb5a6124-143a-4762-9294-538a78a98bd8
      metricId: a2d0dcbb-9bb6-4f34-83c6-6716ba29a357
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Performance
      legendName: p99
      min: 0
      max: 500
      incident:  
    - entityId: fb5a6124-143a-4762-9294-538a78a98bd8
      metricId: f4d0e7dc-f56b-4ee1-b3ff-41b8b4d854ec
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Performance
      legendName: p95
      min: 0
      max: 150
      incident:  
    - entityId: 48449373-bb83-4280-b45c-484fe89f5943
      metricId: b1e087cd-f699-478b-b0fa-10e9ea4d2251
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: TPM
      legendName: TPM
      min: 0
      max: 150
      incident:  
    - entityId: e5146d1f-39f8-4d14-a43c-b14ff4755ddb
      metricId: 441a5a8f-d8e1-42ea-bbe6-72d416bec649
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
    - entityId: fa1e6269-ef44-4b7c-bf10-f75f9017c274
      metricId: bb8b25af-0e10-4d4f-9931-5b4ab2922045
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: fb5a6124-143a-4762-9294-538a78a98bd8
      metricId: 0c156baf-3965-4ecd-8c6a-0bf0b04627ba
      parentEntityId: 71c51ee6-e336-4419-bc34-82374656e1a8
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 500
