source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: cba970e2-daa5-41ae-a96c-d1b355f0a341
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: ad5c973e-9b0f-497f-9a6b-195b0fe24bc8
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: 59354628-747a-4ba1-b739-830d1a44e8f2
      metricId: 0c1d4f90-1f08-4452-93eb-358f255e6efa
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 150
    - entityId: 59354628-747a-4ba1-b739-830d1a44e8f2
      metricId: 77f7f88a-528c-4769-83f8-f4f7289ff164
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Performance
      legendName: p99
      min: 0
      max: 150
      incident:  
    - entityId: 59354628-747a-4ba1-b739-830d1a44e8f2
      metricId: 95dd56e9-d7f8-433a-b4fb-4786fbcc9f67
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Performance
      legendName: Average
      min: 0
      max: 10
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 5263c8eb-d922-4ec1-8abb-f3ec6c46d43d
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 73d84d87-23d2-427a-a30c-d3fdf21540b3
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 85bd13c9-c209-4784-beb2-68aa8a3ef295
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 85f3d7a1-7c37-4778-b43e-0fb5fc515bcc
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: 5704b889-d7ac-45d1-98b6-9139afcb00a4
      metricId: 793c8e60-b022-4468-9b11-1fcdb9a2bfad
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 0178e183-5464-48f8-9eed-6cf970c3694e
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: a0d207f7-5d63-4bcc-a5fc-c1f1c3412af4
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: 59354628-747a-4ba1-b739-830d1a44e8f2
      metricId: 1b1934f3-295a-4cf8-a600-ebe37687244a
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Performance
      legendName: p95
      min: 0
      max: 10
      incident:  
    - entityId: 59354628-747a-4ba1-b739-830d1a44e8f2
      metricId: 3988b932-0e5d-4be6-8da4-b262deba7362
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 150
      incident:  
    - entityId: be392e83-88b4-4e42-b588-89816ede2a94
      metricId: 610e034b-28c1-47b4-bdc7-a02a0ff1ebe0
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 500
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 17b58f04-6b13-4ae7-85e5-20891639471e
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 7c309b5a-6e3d-4856-a6f9-5cd37c1fe4ee
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: 9881d1fb-216f-41ab-b47f-24f0b74648c6
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: 9679404c-8d40-4932-ade5-e3192094eb12
      metricId: c9423121-98db-4610-b624-818bedbb0946
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_S
      min: 0
      max: 15
      incident:  
