source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: c7a22ab6-d233-46ad-8634-9a491a36c8a8
      metricId: 7998ec38-3ad6-467d-9d79-b10643958ab9
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 150
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: e2646149-8d8e-48a7-a64b-a9aa7ecac4d0
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 3a4df27a-702e-4f48-9cee-6f18c0e84a09
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: c7a22ab6-d233-46ad-8634-9a491a36c8a8
      metricId: 2d7baa2b-4f81-4ae7-ae68-64f7d9b506b7
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Performance
      legendName: Average
      min: 0
      max: 5
      incident:  
    - entityId: 66c53cf4-b746-4ecc-aa59-3fc1f697f94d
      metricId: 42f767ee-f492-4efa-b4b5-01d8f1ce4a56
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 500
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: ed6810ee-fc36-40eb-8705-ecdee24de551
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: fd41eb87-2b30-4dc2-b063-1bb4c7281512
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: bbda74fc-f488-479d-804f-ee4043568eb6
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 22f5ee3f-49a7-474f-bd0b-ca22ee78ca14
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 2acfde01-126f-47e8-b46b-b7f493364047
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: be9fbd57-fe7d-4f1d-9232-45c61af5d731
      metricId: 8cb7d179-5ef7-42a7-b52d-671dcbfd5ac7
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 7c636527-9bbb-4526-b69a-6885fa6c7382
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 9642618d-f63e-46b2-8262-542aecb1112e
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: 3051d2de-d28d-490c-ba57-4ee0aec5c4f0
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: a43a4632-bd60-402c-8b52-266362fb4987
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_T
      min: 0
      max: 15
      incident:  
    - entityId: f4b7a182-17ee-439d-a707-971ac56221d5
      metricId: b2b46622-675f-4cf1-8545-b1ca155d3feb
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_S
      min: 0
      max: 15
      incident:  
    - entityId: c7a22ab6-d233-46ad-8634-9a491a36c8a8
      metricId: 6dd494dd-922d-46d4-b3e2-6b73bfa62252
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Performance
      legendName: p99
      min: 0
      max: 150
      incident:  
    - entityId: c7a22ab6-d233-46ad-8634-9a491a36c8a8
      metricId: e14eb121-2771-4770-8e9c-488a80a34957
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 200
      incident:  
    - entityId: c7a22ab6-d233-46ad-8634-9a491a36c8a8
      metricId: 63b93723-e160-497a-aadb-269c3595304b
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Cards DB
      graphName: Performance
      legendName: p95
      min: 0
      max: 100
      incident:  
