source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: ee502697-79b0-4aa1-8eba-950a92134acd
      metricId: 0f8c3adf-7929-4f1e-bdb2-33771c6b2fa2
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: TPM
      legendName: TPM
      min: 0
      max: 800
      incident:  
    - entityId: 131c1521-af61-4c7b-9f1e-a12a19d2bef8
      metricId: b84db774-cf05-4296-89fe-fa4ea86ff834
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: 7365830b-8e4a-41fa-9bb4-5f0cdcbd808f
      metricId: 97b73b58-deca-4ea7-bc23-77159309215b
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 250
    - entityId: 7365830b-8e4a-41fa-9bb4-5f0cdcbd808f
      metricId: 8908825d-b433-4e5c-aa83-1c893fd9b7df
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Performance
      legendName: p99
      min: 0
      max: 250
      incident:  
    - entityId: 7365830b-8e4a-41fa-9bb4-5f0cdcbd808f
      metricId: a3e7c684-26ac-4322-a05c-141d7f2b0c5a
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 250
      incident:  
    - entityId: 7365830b-8e4a-41fa-9bb4-5f0cdcbd808f
      metricId: 90f3346b-9b12-454b-b12f-3c4540831d27
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Performance
      legendName: p95
      min: 0
      max: 15
      incident:  
    - entityId: 6730373d-2783-4f35-9f40-f747abfacb2c
      metricId: 120746d8-7e0b-4138-a465-676e3561a364
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Error
      legendName: Failure
      min: 0
      incident:  
    - entityId: 6730373d-2783-4f35-9f40-f747abfacb2c
      metricId: 4c2dd8aa-f6c9-446a-866a-f3e73ed27c8c
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Error
      legendName: Exception
      min: 0
      incident:  
    - entityId: 7365830b-8e4a-41fa-9bb4-5f0cdcbd808f
      metricId: 81fd8ed9-ea42-4a0f-9ebf-f373074e4e5e
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Redis
      graphName: Performance
      legendName: Average
      min: 0
      max: 15
      incident:  
