source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 72a4e1cf-2b68-43fd-b2f0-8cc3782bd1ff
      metricId: 072f3083-bc68-4b97-8a52-7617aa3a384f
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
      incident:  
    - entityId: 7e968ed7-1d60-4b9e-8e6c-e4a71e123c6d
      metricId: 4a39e5c6-78ba-4367-8526-6db71f9fcaad
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Error
      legendName: Exception
      min: 0
      max: 40
      incident:  
    - entityId: 7e968ed7-1d60-4b9e-8e6c-e4a71e123c6d
      metricId: 7e0884cd-d45d-457b-a4b5-90d05bfdae37
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
    - entityId: 72a4e1cf-2b68-43fd-b2f0-8cc3782bd1ff
      metricId: e5295cc7-570d-4ccf-8ae6-c211dac48791
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: 72a4e1cf-2b68-43fd-b2f0-8cc3782bd1ff
      metricId: 8b357a53-c23e-414e-b5f0-3a3e5042594d
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Performance
      legendName: p95
      min: 0
      max: 750
      incident:  
    - entityId: 72a4e1cf-2b68-43fd-b2f0-8cc3782bd1ff
      metricId: 23ffc0df-9748-4890-9f51-a86f99236a7b
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Performance
      legendName: Average
      min: 0
      max: 500
      incident:  
    - entityId: 0195d01e-5bc9-4021-92f2-0ad2a02ccf0d
      metricId: bdf06c74-513b-4f39-9bd5-6d936ce43f9d
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: TPM
      legendName: TPM
      min: 0
      max: 200
      incident:  
    - entityId: bced7888-2982-4568-a97e-f309bb5b3853
      metricId: 563a7e9f-bdd0-4eeb-b5f0-41f7bcfca699
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 72a4e1cf-2b68-43fd-b2f0-8cc3782bd1ff
      metricId: 859b7d00-519b-464d-a663-a23f643cf089
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - Validate OTP
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2000
      incident:  
