source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: f94540c0-b61d-4010-93b6-f4bf9d366dd9
      metricId: 88faf0b3-bcac-4807-b470-f4587dd912ad
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 5000
      incident:  
    - entityId: 5144917d-9a94-48ea-8037-b86aaaf2629e
      metricId: 017a7177-ab50-40ca-9da5-6ecf924786a6
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: TPM
      legendName: TPM
      min: 0
      max: 250
      incident:  
    - entityId: 8297f5c5-a44a-4f54-8046-9040baf79656
      metricId: 49bec97f-d93c-4def-be7d-75e3ef2f8c04
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
      incident:  
    - entityId: 8297f5c5-a44a-4f54-8046-9040baf79656
      metricId: e048a2dc-ff40-4984-92f4-7c9ed351628f
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Error
      legendName: UserException
      min: 0
      max: 50
      incident:  
    - entityId: 8f35f890-8593-4505-ba3d-f47f3266ea5d
      metricId: 1b2364d9-583d-440b-8f28-74f113e796c6
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: f94540c0-b61d-4010-93b6-f4bf9d366dd9
      metricId: 5e4589b2-0fbf-4c89-b8ec-7112c312647f
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Performance
      legendName: Average
      min: 0
      max: 1500
      incident:  
    - entityId: f94540c0-b61d-4010-93b6-f4bf9d366dd9
      metricId: 80333880-71e9-4348-8cc1-cb49f49122d1
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Performance
      legendName: p99
      min: 0
      max: 4000
      incident:  
    - entityId: f94540c0-b61d-4010-93b6-f4bf9d366dd9
      metricId: 22c0160d-6315-48f8-be25-ff6747a3733e
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 5000
    - entityId: f94540c0-b61d-4010-93b6-f4bf9d366dd9
      metricId: e8c2b6f1-5aeb-4154-ba52-9191837e5086
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: 8297f5c5-a44a-4f54-8046-9040baf79656
      metricId: 21cfcb85-dcd0-4985-af41-e18f3c34f38e
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: Get Challenge API stats - POD
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
