source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: b7b30941-359f-431b-b571-92cd63fb0dd8
      metricId: 7d540420-7519-4b62-936c-66a06f27da99
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 300
    - entityId: b7b30941-359f-431b-b571-92cd63fb0dd8
      metricId: f30cbe95-c059-4849-a31f-532334ca30cf
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: Average
      min: 0
      max: 10
      incident:  
    - entityId: c25a0d8e-66e5-46e6-a581-0ce86723f563
      metricId: b6511185-1cc9-4528-b85f-58baa1e25bc0
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident: sev2
    - entityId: 6e79caa0-765f-47ad-ac59-7902f705da8d
      metricId: e8b14df6-8e3d-4eca-b518-dd3541a1baba
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 500
      incident:  
    - entityId: b7b30941-359f-431b-b571-92cd63fb0dd8
      metricId: 7170f1fb-f6a7-49dd-9e40-a36b6d3becae
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p95
      min: 0
      max: 40
      incident:  
    - entityId: 2ec3117d-91e6-438f-878f-9b69a5de952b
      metricId: 78b7d851-01ef-4013-af39-d30dec61d5dc
      parentEntityId: b90c97f8-267c-4b96-8061-8e90318d4a0d
      containerName: Biometric Login Availability Dependencies
      graphName: Known Device DB
      legendName: Availability
      min: 98
      max: 99.9
      incident: sev2
    - entityId: 6e79caa0-765f-47ad-ac59-7902f705da8d
      metricId: f8010829-fb05-48ab-b823-219c1efa6921
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Performance
      legendName: p95
      min: 0
      max: 250
      incident:  
    - entityId: 6e79caa0-765f-47ad-ac59-7902f705da8d
      metricId: a7065ce6-9bf3-4b09-a28f-df71a6826311
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 400
    - entityId: 23ba54b9-774e-498b-a38b-eb424e4ca6f9
      metricId: 9bdcc8d7-4bda-44d6-8c05-fc8a681d844c
      parentEntityId: b90c97f8-267c-4b96-8061-8e90318d4a0d
      containerName: Biometric Login Availability Dependencies
      graphName: MFA DB
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: b7b30941-359f-431b-b571-92cd63fb0dd8
      metricId: 4d0206ea-f6cc-4bf9-9916-9d342b8c29e8
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99
      min: 0
      max: 50
      incident:  
    - entityId: 6e79caa0-765f-47ad-ac59-7902f705da8d
      metricId: 75b31442-ca79-416f-b101-bc58cd7f7cab
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Performance
      legendName: p99
      min: 0
      max: 400
      incident:  
    - entityId: 7c6402f8-1390-415f-8916-8968e85737bd
      metricId: fd6c2f15-be2f-44b0-a071-849b4586b4b8
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident: sev2
    - entityId: ee949908-4a8a-445a-a91d-ad6b6e36abc9
      metricId: 7b57a77f-b1d1-4e6c-bc40-8d8d85aaafa8
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: TPM
      legendName: Count
      min: 0
      max: 8000
      incident:  
    - entityId: b7b30941-359f-431b-b571-92cd63fb0dd8
      metricId: df98028d-1741-4d4a-98ca-b62b471932a7
      parentEntityId: 1ee5c1cc-3fa3-4a0c-9eb9-adaed38b987b
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 500
      incident:  
    - entityId: df3af714-c851-4c38-888c-b05dc04fe9a4
      metricId: f447ee7e-c97d-4bb5-ae70-03e8f709b2fc
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: TPM
      legendName: Count
      min: 0
      max: 9000
      incident:  
    - entityId: 6e79caa0-765f-47ad-ac59-7902f705da8d
      metricId: 7e90da8d-c978-4be6-a716-608441bc3ce2
      parentEntityId: 5beb4a02-64de-4008-895f-161459c05de9
      containerName: KnownDevice DB Availability Golden Signals
      graphName: Performance
      legendName: Average
      min: 0
      max: 250
      incident:  
