source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: a4d37812-2ae2-46cc-a64b-5e1536760a57
      metricId: 4a657d8b-f8b5-492f-a3c7-a84382e76856
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p95
      min: 0
      max: 800
      incident:  
    - entityId: a4d37812-2ae2-46cc-a64b-5e1536760a57
      metricId: aa4f8565-e150-41f2-97ef-cd86f5edd5ad
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99
      min: 0
      max: 1200
      incident:  
    - entityId: a053b07f-c78b-41cf-8486-2db44a83e46c
      metricId: 0e3b9599-9142-4e30-ac82-63ed778451c2
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: a053b07f-c78b-41cf-8486-2db44a83e46c
      metricId: f169b278-076a-42e4-8b52-574643909471
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Error
      legendName: Exception
      min: 0
      max: 50
      incident:  
    - entityId: 653db641-56cc-4f0e-82c7-27e2e7dad392
      metricId: 0e4b33bb-ac1a-40c4-b247-66d645e09796
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: TPM
      legendName: TPM
      min: 0
      max: 800
      incident:  
    - entityId: 9fa9f1d7-39ea-4e85-8d07-5136b286abc3
      metricId: fa547644-276c-49d4-8289-9ff3bc9bfc95
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: a4d37812-2ae2-46cc-a64b-5e1536760a57
      metricId: 075cf943-9377-41dd-b1ec-274c0ace6007
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: a4d37812-2ae2-46cc-a64b-5e1536760a57
      metricId: ac24e513-528f-4c9e-af33-9f92158dd864
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: a4d37812-2ae2-46cc-a64b-5e1536760a57
      metricId: d8a3d8b2-3c1c-426a-8293-44eed01cda47
      parentEntityId: f1b7427c-a824-4040-98ee-5076d162e2ef
      containerName: OTP AuthN - Get Eligible OTP channels
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
