source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 079ca5ab-bff9-47d3-9297-5e48389b0bc2
      metricId: 53b5768d-9865-428f-8c9f-4097b7574d74
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Performance
      legendName: Average
      min: 0
      max: 500
      incident:  
    - entityId: 079ca5ab-bff9-47d3-9297-5e48389b0bc2
      metricId: 72d2ff35-209a-4b31-825f-4fff674717b4
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Performance
      legendName: p99
      min: 0
      max: 3000
      incident:  
    - entityId: d42f84d2-2d65-4ec6-afc4-6a2b6a8d036c
      metricId: 56d7f954-17d6-4484-8691-f1880b86deba
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: TPM
      legendName: TPM
      min: 0
      max: 900
      incident:  
    - entityId: 81fe0b7e-18d8-447d-9db9-721852252ec2
      metricId: 9b0307c4-0dee-4900-ac0b-ee92d767134b
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Error
      legendName: Failure
      min: 0
      max: 10
      incident:  
    - entityId: 4f193ff1-60c7-49db-a653-c21d01c12386
      metricId: 95ef3939-1f76-495e-8c9f-6876db1dbf54
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Availability
      legendName: Availability
      min: 97
      max: 100
      incident: sev2
    - entityId: 079ca5ab-bff9-47d3-9297-5e48389b0bc2
      metricId: 056a7b93-4ab6-468b-94fe-118609f6fe08
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: 079ca5ab-bff9-47d3-9297-5e48389b0bc2
      metricId: 2094782e-9de8-499d-a926-bc5b35c88396
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Performance
      legendName: p95
      min: 0
      max: 1000
      incident:  
    - entityId: 079ca5ab-bff9-47d3-9297-5e48389b0bc2
      metricId: 42deb7de-d3f9-4577-96d4-8fc196aa3719
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: Demographic
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 3000
      incident:  
