source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: f11813db-743e-4c26-addc-430d0b4a2862
      metricId: 162a8508-74d2-4823-ae4d-096528fab1b7
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 50c3ee96-1d7b-4b51-9414-62f772608b2e
      metricId: 114db1d3-cd02-4aa1-b9a8-099c955b65c0
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Performance
      legendName: Average
      min: 0
      max: 400
      incident:  
    - entityId: 50c3ee96-1d7b-4b51-9414-62f772608b2e
      metricId: 515a852b-1213-4f66-92d2-060d20c4b8f0
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Performance
      legendName: p95
      min: 0
      max: 600
      incident:  
    - entityId: 50c3ee96-1d7b-4b51-9414-62f772608b2e
      metricId: 6642b8bb-80ab-4b66-bd36-4c81b8ef20c9
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: 50c3ee96-1d7b-4b51-9414-62f772608b2e
      metricId: d330ff1e-e23f-4c63-a548-31a74eaff78c
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: 50c3ee96-1d7b-4b51-9414-62f772608b2e
      metricId: ff5e1b3c-4526-4fa3-8768-d111e54fbd85
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: 741a3eaa-5ea6-4e0e-93b4-29670c5d16d7
      metricId: 19cc2ace-79b1-4cb1-982a-d25654097fa0
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Error
      legendName: Exception
      min: 0
      max: 50
      incident:  
    - entityId: 741a3eaa-5ea6-4e0e-93b4-29670c5d16d7
      metricId: 256bab9b-3687-4bec-b162-f7b0aa629efd
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: 90d02e5b-0a6a-43ba-b6e5-6e3a56bce534
      metricId: bc35f6b1-ee18-4d4e-8a7b-717abadfccf3
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - PUSH Delivery
      graphName: TPM
      legendName: TPM
      min: 0
      max: 350
      incident:  
