source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 966c5cf5-fcbc-4a1a-bf42-b539058522a9
      metricId: d028e8e6-b839-442a-ac7e-15cec5c6c1f3
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Availability
      legendName: Availability
      min: 94
      max: 100
      incident: sev2
    - entityId: 2f91be86-6d37-442e-93d2-78a4ce070b9d
      metricId: ac37114e-e836-43f5-a4a8-85bdbeddeac1
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Performance
      legendName: Average
      min: 0
      max: 1200
      incident:  
    - entityId: 2f91be86-6d37-442e-93d2-78a4ce070b9d
      metricId: 2c381e89-98a5-4056-82e3-cdf91fff72f0
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Performance
      legendName: p99
      min: 0
      max: 3000
      incident:  
    - entityId: 2f91be86-6d37-442e-93d2-78a4ce070b9d
      metricId: ab98d980-e509-45d1-8ac7-15c4c9534e3a
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 5000
      incident:  
    - entityId: 2f91be86-6d37-442e-93d2-78a4ce070b9d
      metricId: bd0a5779-9c07-4a69-865f-9c7b1754abd6
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: 2f91be86-6d37-442e-93d2-78a4ce070b9d
      metricId: b69e9a63-8923-4795-b7a9-1793a981e206
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 5000
    - entityId: 489f0aa5-2265-4247-9127-b30b34fc53fb
      metricId: 4f4edcc1-f0f4-41b1-95ca-6a169617815b
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: TPM
      legendName: TPM
      min: 0
      max: 300
      incident:  
    - entityId: e2c70be4-1c47-4265-b85d-b0b5be73562c
      metricId: 1c85d096-1094-40c3-a928-325eeac730ae
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: DCP
      graphName: Error
      legendName: Failure
      min: 0
      max: 15
      incident:  
