source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 9f2f5ed8-4812-4c73-9b83-6da01796f8a9
      metricId: 1e114bfc-815e-4402-8ebc-47900c90b4d7
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 750
    - entityId: 9f2f5ed8-4812-4c73-9b83-6da01796f8a9
      metricId: 10458fc5-5656-4f8a-9139-e9992ef35e35
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 750
      incident:  
    - entityId: c82c5870-13bd-4b80-a86a-d0238f3f2fca
      metricId: f259bdff-ff7c-4a48-82df-8afbadd4ef0b
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Error
      legendName: Exception
      min: 0
      max: 25
      incident:  
    - entityId: 9a8c0097-8889-4073-bff8-e6c7853dc8dc
      metricId: d35ede31-5fa7-4cea-8f7f-dcdf275812a8
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: 9f2f5ed8-4812-4c73-9b83-6da01796f8a9
      metricId: 823116a4-d636-4fab-b646-39fb78b6b874
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: c82c5870-13bd-4b80-a86a-d0238f3f2fca
      metricId: fd339c10-11c7-49cc-b285-deed34d6ba5e
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Error
      legendName: Failure
      min: 0
      max: 15
      incident:  
    - entityId: 21a3ad83-7df2-4b41-9243-12c52c705de5
      metricId: 26075beb-ebe8-464c-9ada-cab28b60c775
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 750
      incident:  
    - entityId: 9f2f5ed8-4812-4c73-9b83-6da01796f8a9
      metricId: 0b417d86-9109-4240-9cf5-c1fd3b0062dc
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Performance
      legendName: p95
      min: 0
      max: 350
      incident:  
    - entityId: 9f2f5ed8-4812-4c73-9b83-6da01796f8a9
      metricId: 56f0bd3a-00e9-403f-90d0-744f3e4ee042
      parentEntityId: caf29f4f-de4a-4956-9b80-61533e128859
      containerName: Lockout DB
      graphName: Performance
      legendName: p99
      min: 0
      max: 750
      incident:  
