source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 0573d6bb-6a91-4e77-acfb-7f66d7a90ebf
      metricId: ac4e8ecb-8015-4ba0-9f91-5890946586a3
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 4000
    - entityId: ece54840-066c-4805-a90c-6c3a68b4c572
      metricId: ce59bbca-ae6d-4145-868e-bf36fa70482b
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Error
      legendName: Exception
      min: 0
      max: 50
      incident:  
    - entityId: 60dce3c6-a33f-4056-9bb9-db1d49bb1b9a
      metricId: 3d136d64-6cdf-4919-b057-3b5d887d9c2f
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: TPM
      legendName: TPM
      min: 0
      max: 700
      incident:  
    - entityId: 58e80f2c-8ae0-4063-af09-1c5bd82ba9db
      metricId: b8fcb411-ffb8-4389-af3c-087c80ff102a
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 0573d6bb-6a91-4e77-acfb-7f66d7a90ebf
      metricId: 0170ef62-1b35-402d-8d11-cf41abba7baf
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Performance
      legendName: Average
      min: 0
      max: 800
      incident:  
    - entityId: 0573d6bb-6a91-4e77-acfb-7f66d7a90ebf
      metricId: 91d87223-a957-47d9-8f20-9105594b0683
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 4000
      incident:  
    - entityId: 0573d6bb-6a91-4e77-acfb-7f66d7a90ebf
      metricId: a1322444-0b88-4225-8550-3344c3a2b5fc
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: 0573d6bb-6a91-4e77-acfb-7f66d7a90ebf
      metricId: d6579220-585b-4895-a9d7-3edf315a1372
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Performance
      legendName: p99
      min: 0
      max: 4000
      incident:  
    - entityId: ece54840-066c-4805-a90c-6c3a68b4c572
      metricId: 6613fb75-efca-4d68-a8fc-2056faf79f7d
      parentEntityId: 815f026f-410f-4815-a070-57ec66acd4a7
      containerName: OneAuth - Get Challenge API stats
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
