source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 8976d1e8-5bb9-4ec9-bea3-dca49ec1d531
      metricId: ab8c6df2-f1f7-4912-bbdd-1404fca81b7b
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p95
      min: 0
      max: 350
      incident:  
    - entityId: 8976d1e8-5bb9-4ec9-bea3-dca49ec1d531
      metricId: 6dc0a1fc-9e21-4289-a7fb-67ed2dac3832
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99
      min: 0
      max: 750
      incident:  
    - entityId: bd8a2052-a65b-410f-9ad8-5698e4f8b0e9
      metricId: b2804b19-aed1-423f-9160-bed7c044f3fc
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Error
      legendName: Failure
      min: 0
      max: 30
      incident: sev2
    - entityId: 8650bb0f-db39-4058-ac54-4d16e9255d8d
      metricId: 9768103f-fd8a-431b-bdf7-4537aafda986
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: 8976d1e8-5bb9-4ec9-bea3-dca49ec1d531
      metricId: 55671f2d-bddc-4a6b-ab1c-e0bc4207491a
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: Average
      min: 0
      max: 250
      incident:  
    - entityId: 8976d1e8-5bb9-4ec9-bea3-dca49ec1d531
      metricId: a801b464-c92b-496d-af24-f2f3efe149f3
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1200
      incident:  
    - entityId: 8976d1e8-5bb9-4ec9-bea3-dca49ec1d531
      metricId: 2b21de21-c31a-4279-9b9e-4ce4e7f9c895
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1000
    - entityId: bd8a2052-a65b-410f-9ad8-5698e4f8b0e9
      metricId: 1f43a054-cb2a-4e47-b5f6-4fbcbbc260d2
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: Error
      legendName: Exception
      min: 0
      max: 500
      incident:  
    - entityId: 4a9256e1-ba3f-49b5-a269-29fad6772b75
      metricId: 911df13a-5e5a-415e-8a07-855f2998d79d
      parentEntityId: 9c132c89-9bce-49e0-95cd-19db4f73f6e5
      containerName: TOTP Read Registration Service
      graphName: TPM
      legendName: TPM
      min: 0
      max: 500
      incident:  
