source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 5b268abf-f5f2-408d-8781-19bdfa867d97
      metricId: 3b9a44ae-2c32-442f-b56a-35b0de2c3137
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: 48e023ad-bdc7-495e-b0ee-9118a79fb074
      metricId: 487764e9-3473-403f-9d80-a0b27417a88d
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: 48e023ad-bdc7-495e-b0ee-9118a79fb074
      metricId: aa1b01f9-5865-4cad-a69e-a94a07174335
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: 10713117-a00c-4391-841c-f6ec63361c8d
      metricId: b8a5a647-3fac-409b-80f4-8ae04581e3b4
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: 48e023ad-bdc7-495e-b0ee-9118a79fb074
      metricId: 3230668d-bc49-49d6-b7bd-06256c3019fb
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Performance
      legendName: p99
      min: 0
      max: 1000
      incident:  
    - entityId: 48e023ad-bdc7-495e-b0ee-9118a79fb074
      metricId: c8a94f5a-d05f-4df2-b95c-912463903736
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Performance
      legendName: p95
      min: 0
      max: 350
      incident:  
    - entityId: 48e023ad-bdc7-495e-b0ee-9118a79fb074
      metricId: b86a771a-1143-4277-b290-cb2abba0e94f
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: 10713117-a00c-4391-841c-f6ec63361c8d
      metricId: c6845f73-7f8c-4e79-ba7d-42a452051303
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: Error
      legendName: Exception
      min: 0
      max: 30
    - entityId: bc62bebb-e72e-4b8e-8d98-7430a6ec6eb1
      metricId: e831f644-319f-4b33-af57-7d5094df42ae
      parentEntityId: 73db5020-59d8-4048-a214-29f6c9022526
      containerName: Lockout DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 1200
      incident:  
