source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 55ad20c1-b55c-411f-a745-c3598534c928
      metricId: d8b02879-b514-439a-9831-bf7df48a2734
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Error
      legendName: UserException
      min: 0
      incident:  
    - entityId: 55ad20c1-b55c-411f-a745-c3598534c928
      metricId: 4b511cf6-93d5-4c6b-99b9-8c01bde4a3e0
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
    - entityId: 36f2a428-6e63-48eb-8f53-ac0121676cb0
      metricId: b1b28ce1-1003-445a-8cf3-8ab3d524deef
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Availability
      legendName: Availability
      min: 94
      max: 100
      incident: sev2
    - entityId: bc987dc1-6997-4dae-a14b-cec9b6676e11
      metricId: b075a71c-b0a5-4f35-9e5c-f315f29467d3
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: bc987dc1-6997-4dae-a14b-cec9b6676e11
      metricId: d79b5758-a86e-4c0d-bb67-bdd19b5081ab
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Performance
      legendName: p95
      min: 0
      max: 100
      incident:  
    - entityId: bc987dc1-6997-4dae-a14b-cec9b6676e11
      metricId: 4fe23c92-2c7e-408a-9917-f78ac226ffd0
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Performance
      legendName: p99
      min: 0
      max: 600
      incident:  
    - entityId: bc987dc1-6997-4dae-a14b-cec9b6676e11
      metricId: 09264dba-62d7-4edd-8a96-cea9ae3a4d0b
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 600
    - entityId: bc987dc1-6997-4dae-a14b-cec9b6676e11
      metricId: 0e54cf24-6e82-4e3a-9623-2d0d30211b72
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 600
      incident:  
    - entityId: b2be01ea-06d1-4cd4-8758-9417974a5add
      metricId: 7a9be0bf-572a-48db-951c-5125d6c48f99
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: TPM
      legendName: TPM
      min: 0
      max: 350
      incident:  
    - entityId: 55ad20c1-b55c-411f-a745-c3598534c928
      metricId: 272d4ada-3d7b-4a25-9c4a-2f15766feb83
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Tokenizer
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
