source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 4e430bc8-d4e2-4836-9d8b-124808a8a74e
      metricId: fd17e2f0-215b-4733-a965-15035a5e2953
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 96
      max: 100
      incident: sev2
    - entityId: f2de1a0c-1a82-4998-b82d-5e3790ee3b04
      metricId: c613087f-eb1c-4212-8a95-4dce0fe6da0b
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 200
      incident:  
    - entityId: f2de1a0c-1a82-4998-b82d-5e3790ee3b04
      metricId: fab4ca00-40f7-4e4a-af11-7fcff1846101
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 800
      incident:  
    - entityId: f2de1a0c-1a82-4998-b82d-5e3790ee3b04
      metricId: 6ddc9a7e-032b-4384-9e9d-451a07671d31
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: f2de1a0c-1a82-4998-b82d-5e3790ee3b04
      metricId: 697866f3-39a1-4789-a7b8-8532d75ef36a
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: f2de1a0c-1a82-4998-b82d-5e3790ee3b04
      metricId: 3f03606e-309f-4c9b-a943-38a613839ff6
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 800
      incident:  
    - entityId: 92defc31-50c7-4de6-9e88-d636f2460366
      metricId: 0687d35f-b9cf-40fa-9eb0-42e1f8429335
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 0
      max: 3000
      incident:  
    - entityId: 9ed137b8-c0c3-49e5-8c2e-439083fa5184
      metricId: d8a18ff7-7d89-4eb2-a03b-1badc773dc85
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
