source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: beed9107-fb93-45db-b00e-0ab7917744ec
      metricId: 7f6867f9-72ac-42c8-b2a9-02a8ac34d3be
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: beed9107-fb93-45db-b00e-0ab7917744ec
      metricId: 2c459c20-b06a-4513-860c-a5b0bc46824e
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2500
      incident:  
    - entityId: beed9107-fb93-45db-b00e-0ab7917744ec
      metricId: ad481363-cf69-4377-84f8-5d24781fad0d
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 350
      incident:  
    - entityId: 2246a07b-9dbd-4d11-92d8-df2f403b87ef
      metricId: 7377d4ad-8782-4244-bf38-4ea3b3faf25d
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 0
      max: 200
      incident:  
    - entityId: a679cb04-3af6-44a8-9f30-0189c0d39b81
      metricId: 96f2bc4a-cf89-452c-9128-346714d0eef1
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
    - entityId: 34eaade1-f633-43ee-abea-1e71f2edae9f
      metricId: 293bc21b-5397-4a42-bc34-7a1c69395210
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: beed9107-fb93-45db-b00e-0ab7917744ec
      metricId: 0aca7cd1-d666-46fd-93f8-ed40a6070de8
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
    - entityId: beed9107-fb93-45db-b00e-0ab7917744ec
      metricId: 0d67b678-08ae-4130-b03a-0c00c6a08aa5
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 500
      incident:  
