source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: e5e0a2f9-f3a0-4ea4-85f1-fa34219c2263
      metricId: efd504d1-d829-4b5a-9516-851ce6cd5739
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Performance
      legendName: Average
      incident:  
    - entityId: e5e0a2f9-f3a0-4ea4-85f1-fa34219c2263
      metricId: b28d4db2-b620-4c1a-a4aa-d23153d31443
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Performance
      legendName: p99.99
      incident:  
    - entityId: 28f31033-3d60-4e2b-8f94-9468f0ebbf59
      metricId: 5894cd7f-fb91-4693-b5af-61642d35201f
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Error
      legendName: Exception
      incident:  
    - entityId: 28f31033-3d60-4e2b-8f94-9468f0ebbf59
      metricId: aee48f31-ac2d-4750-a5a3-e7bcb56a3641
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Error
      legendName: Failure
    - entityId: 9c2fc74f-49a0-41fb-88b5-9187e6c59b65
      metricId: 61ee6107-7239-498e-8936-80a06fdf0dbf
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: TPM
      legendName: TPM
    - entityId: 5a5553e6-eebe-42e4-a41b-ff7daf5a25b0
      metricId: 44b304cc-e0ca-4015-a924-b61168371742
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Availability
      legendName: Availability
    - entityId: e5e0a2f9-f3a0-4ea4-85f1-fa34219c2263
      metricId: f1bfda2d-54b3-4d6d-b855-cb8581d5e465
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Performance
      legendName: p99.9
    - entityId: e5e0a2f9-f3a0-4ea4-85f1-fa34219c2263
      metricId: 7d961dea-add7-45a8-b8ec-dbde467e92a3
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Performance
      legendName: p95
      incident:  
    - entityId: e5e0a2f9-f3a0-4ea4-85f1-fa34219c2263
      metricId: 69b4cd47-896d-477d-bbc6-dff8e586b65d
      parentEntityId: 26d4f8ca-a840-4a13-904e-d7b17b04064c
      containerName: Agent Binding Validate signature
      graphName: Performance
      legendName: p99
      incident:  
