source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: f3a077f5-956d-49b7-82cb-6222e4677535
      metricId: 47c0e88d-aab6-4109-942e-3d2d7e39135a
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: ca083919-4db7-4d32-a626-e26c3277b4b9
      metricId: 564fd6db-3e39-436b-90fc-8ca5e44e5469
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1500
    - entityId: c27a270f-fc64-41f5-99c4-20b1d54c3be2
      metricId: cbedefc1-1588-45b8-8653-45b8778d4160
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 0
      max: 350
      incident:  
    - entityId: b362e85b-fbac-4ec7-8d33-358b86fae67d
      metricId: 9b1dd67c-ceaa-40f6-aa70-8d95b093042b
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
    - entityId: ca083919-4db7-4d32-a626-e26c3277b4b9
      metricId: dec11fe9-2f9a-480a-8b0d-85c75b16b9d3
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 450
      incident:  
    - entityId: ca083919-4db7-4d32-a626-e26c3277b4b9
      metricId: d4ef24a6-c1f9-4e96-8607-1c144c3e6ba3
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: ca083919-4db7-4d32-a626-e26c3277b4b9
      metricId: d184d2b6-fbce-453f-aa86-0203e09ffd68
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 500
      incident:  
    - entityId: ca083919-4db7-4d32-a626-e26c3277b4b9
      metricId: a0e491eb-d76b-4de4-8b86-7484213aab62
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: b362e85b-fbac-4ec7-8d33-358b86fae67d
      metricId: f215a770-6cf0-4c98-b092-302da6c74a87
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
    - entityId: b362e85b-fbac-4ec7-8d33-358b86fae67d
      metricId: 2a73e9f5-12ac-4f35-8f5d-b0be1898c9b4
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: MemberService
      graphName: Error
      legendName: UserException
      min: 0
      incident:  
