source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 0bd175a1-8caf-4f2c-998c-5dd1ad3c69b8
      metricId: ac0af16a-f589-46e2-866d-d7b5217a2561
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login opt in markets
      legendName: Challenge Count
      min: 20
      max: 200
      incident:  
    - entityId: 639edce0-1c3b-4a96-9e2e-a447071f1b9b
      metricId: cebc5ea1-e47d-4036-94ad-aca2e2961d17
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Performance
      legendName: p999.Response
      min: 0
      max: 3500
      incident:  
    - entityId: d07bbd35-1fe1-4eed-b284-50ca5b3e5c35
      metricId: 4096b693-d777-453f-85b0-cb72638df275
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login hits from psd2 markets
      legendName: Challenge Count
      min: 20
      max: 1200
      incident:  
    - entityId: d07bbd35-1fe1-4eed-b284-50ca5b3e5c35
      metricId: 4e66f1dd-ae67-4fbb-a3f3-587db7fe0b5d
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login hits from psd2 markets
      legendName: Proceed Count
      min: 20
      max: 2500
      incident:  
    - entityId: d07bbd35-1fe1-4eed-b284-50ca5b3e5c35
      metricId: cbc08568-f79c-4227-b696-8746d645c468
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login hits from psd2 markets
      legendName: Total Count
      min: 50
      max: 4000
      incident:  
    - entityId: 0bd175a1-8caf-4f2c-998c-5dd1ad3c69b8
      metricId: 20aef81f-53f0-44ae-8e36-1ab82714970a
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login opt in markets
      legendName: Total Count
      min: 50
      max: 700
      incident:  
    - entityId: 0bd175a1-8caf-4f2c-998c-5dd1ad3c69b8
      metricId: 4c2d5d87-7e5f-4d29-bba1-873412100f40
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: TPM - web login opt in markets
      legendName: Proceed Count
      min: 20
      max: 400
      incident:  
    - entityId: 8321b3b6-f055-4120-84cf-762697a32919
      metricId: 61f3ad10-bcdf-4c4d-9aaf-973d613d593c
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Web Login CBIS Golden Signals
      legendName: CBIS
      min: 99.9
      max: 100
      incident: sev2
    - entityId: 639edce0-1c3b-4a96-9e2e-a447071f1b9b
      metricId: 63ddcf6b-36b7-4403-a362-95f21fb64975
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Performance
      legendName: p9999.Response
      min: 0
      max: 4000
      incident:  
    - entityId: 639edce0-1c3b-4a96-9e2e-a447071f1b9b
      metricId: 93b0edbf-1d99-4e65-887a-e0b0567df049
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Performance
      legendName: p99.Response
      min: 0
      max: 2500
      incident:  
    - entityId: 639edce0-1c3b-4a96-9e2e-a447071f1b9b
      metricId: c520056d-fdc6-4641-8f0e-7a10f1bfaa87
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Performance
      legendName: p99999.Response
      min: 0
      max: 4000
      incident:  
    - entityId: 639edce0-1c3b-4a96-9e2e-a447071f1b9b
      metricId: ff1e878e-fcab-4140-9ce5-236f500d559a
      parentEntityId: 9f860b09-c718-4641-a70d-f6406273ef88
      containerName: Web Login CBIS Golden Signals
      graphName: Performance
      legendName: Avg.Response
      min: 0
      max: 1200
      incident:  
