source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: c926c086-dd15-432a-93f2-12360992c828
      metricId: 4a896fca-8060-4c14-a1da-b45ed7f1aaa0
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Performance
      legendName: Average
      min: 0
      max: 2000
      incident:  
    - entityId: c926c086-dd15-432a-93f2-12360992c828
      metricId: 0c81a21a-ccf7-4858-9628-5a6fdd76b416
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 5000
      incident:  
    - entityId: 3ca104e7-2ee8-4426-a4e2-551c00c36255
      metricId: 65d77592-0317-40c5-86c9-aed0cf642184
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Error
      legendName: Failure
      min: 0
      max: 15
      incident:  
    - entityId: 3ca104e7-2ee8-4426-a4e2-551c00c36255
      metricId: 75968757-5b2d-4899-a299-70301399b042
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Error
      legendName: BusinessException
      min: 0
      max: 20
      incident:  
    - entityId: 3ca104e7-2ee8-4426-a4e2-551c00c36255
      metricId: 0c237bd0-aaa8-408b-8942-dd1a61909f2e
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Error
      legendName: UserException
      min: 0
      max: 20
      incident:  
    - entityId: 08f494f4-bd21-47be-9836-951fc22dc8bf
      metricId: 3e32a8b8-ecde-419a-9f99-1650d36c1bb7
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: c926c086-dd15-432a-93f2-12360992c828
      metricId: da5adf4f-6f77-490e-9f52-e45d0eaa7c15
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 5000
    - entityId: c926c086-dd15-432a-93f2-12360992c828
      metricId: 4934e622-ed78-4648-8c12-0b301ba4136f
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: c926c086-dd15-432a-93f2-12360992c828
      metricId: a69ec394-0a66-409e-b43d-c731c6b5539b
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: Performance
      legendName: p99
      min: 0
      max: 5000
      incident:  
    - entityId: c53c6fe9-2088-422a-9c60-7501fd05317c
      metricId: 04d580f5-c424-4e49-8fe4-ece751a7440d
      parentEntityId: 4653db05-e47c-436a-af68-1534b0b40467
      containerName: Verf - Get challenge
      graphName: TPM
      legendName: TPM
      min: 0
      max: 300
      incident:  
