source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 4f20cac0-e47c-46d4-a615-34e892cb3b26
      metricId: 21e3e761-23ac-4a56-8abe-623d49ab0b13
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Performance
      legendName: p95
      min: 0
      max: 2500
      incident:  
    - entityId: 4f20cac0-e47c-46d4-a615-34e892cb3b26
      metricId: 804a700c-745e-4755-b9a9-a15fbae7cc6f
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Performance
      legendName: Average
      min: 0
      max: 2500
      incident:  
    - entityId: 4f20cac0-e47c-46d4-a615-34e892cb3b26
      metricId: cc194848-2b42-47c1-9ea9-7c9162ccbf5e
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Performance
      legendName: p99
      min: 0
      max: 2500
      incident:  
    - entityId: 4f20cac0-e47c-46d4-a615-34e892cb3b26
      metricId: 4806a11d-40d9-4b77-86f9-3c23d1afa639
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: 032eb778-5de3-4d8e-8e2f-0c821ca4f7f6
      metricId: fcb151fe-c9cd-49e8-9ba3-9b00adcef80e
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: TPM
      legendName: TPM
      min: 0
      max: 400
      incident:  
    - entityId: 6855ac1b-caeb-4bc3-9f05-fff894b1bcb0
      metricId: e1fd0bbf-4fe9-466c-9c1d-b9cd30da19bd
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Error Rate
      legendName: UserException
      min: 0
      max: 65
      incident:  
    - entityId: 6855ac1b-caeb-4bc3-9f05-fff894b1bcb0
      metricId: f1d85ad7-2dff-481f-8c12-a73345babecc
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Error Rate
      legendName: Failure
      min: 0
      max: 50
      incident: sev2
    - entityId: 6855ac1b-caeb-4bc3-9f05-fff894b1bcb0
      metricId: e96a0d5f-c27f-428f-a484-3d3f7b9e4b93
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Error Rate
      legendName: BusinessException
      min: 0
      max: 10
      incident:  
    - entityId: 86b00797-bca9-42c8-8654-4a3c1667205a
      metricId: 5a7e1496-7a23-469b-98b6-9c0779b67ab2
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Availability
      legendName: Availability
      min: 99.9
      max: 100
      incident: sev2
    - entityId: 4f20cac0-e47c-46d4-a615-34e892cb3b26
      metricId: 21a226d0-fcd8-4d7a-b3e8-d6fc5305de5d
      parentEntityId: f40273c9-cbb7-4e45-9077-cfd7c1cba4df
      containerName: CBIS MFA - Mobile POD
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 3000
      incident:  
