source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 30ca9b6c-58d5-40dc-b3d7-5d98dd4bffb9
      metricId: 606a530f-3746-48cd-9b4f-5689c5a16a7d
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: a25b62ef-e7dd-43e1-bcd4-d518bd8831af
      metricId: 39b21c4e-4176-4772-887e-49704c4188cf
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: a25b62ef-e7dd-43e1-bcd4-d518bd8831af
      metricId: c4509436-7f4a-4bb0-ad82-0c4826de1682
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: a25b62ef-e7dd-43e1-bcd4-d518bd8831af
      metricId: 16267d09-292f-4ca8-86b9-0d09d84866bb
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2000
      incident:  
    - entityId: a25b62ef-e7dd-43e1-bcd4-d518bd8831af
      metricId: 005b3fd0-e221-46f5-a8cf-c7dbcb3d8725
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: p95
      min: 0
      max: 350
      incident:  
    - entityId: a25b62ef-e7dd-43e1-bcd4-d518bd8831af
      metricId: 0763dbcb-8bf3-4d64-a4d8-a72a4cfa3058
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Performance
      legendName: Average
      min: 0
      max: 250
      incident:  
    - entityId: 2db732ad-cf34-414b-92be-636169039c0b
      metricId: b7acf432-9b8a-4fa4-a0ce-ef85c15111ba
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: 2db732ad-cf34-414b-92be-636169039c0b
      metricId: a08a97d5-9f0d-4494-aedb-0f714cbe4188
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: Error
      legendName: Exception
      min: 0
      max: 300
      incident:  
    - entityId: ba743137-0701-4d7a-972d-ad4acbbdac16
      metricId: 32e5e0a0-0ff8-4981-8460-caeef0698b9c
      parentEntityId: e1383d93-4785-49eb-8be7-b9ef94251f93
      containerName: TOTP Read Registration Service
      graphName: TPM
      legendName: TPM
      min: 0
      max: 350
      incident:  
