source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: e6165fdb-11c4-4900-bcb1-844f65555666
      metricId: ebaa84c3-b126-484a-8713-47acbc140963
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Mobile Login Customer Experience
      graphName: Mobile Login Customer Experience
      legendName: CBIS
      min: 99.9
      max: 100
      incident: sev2
    - entityId: b9a7a2b9-52b3-4cf5-9755-82e337bc9e8b
      metricId: 5b3b3661-286b-4353-8c1f-7250e6d36f09
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Mobile Login Customer Experience
      graphName: Mobile Login Customer Experience
      legendName: MFA POA
      min: 99.9
      max: 100
      incident: sev2
    - entityId: 9ec1fbce-7f32-4e47-b7b3-cd454698b123
      metricId: 0c142548-96d1-44c9-9e2d-6c13fac58f0a
      parentEntityId: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
      containerName: Mobile Login Customer Experience
      graphName: Mobile Login Customer Experience
      legendName: MFA POD
      min: 99.9
      max: 100
      incident: sev2
