source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: be7a3360-245d-4131-a2f3-e48d246cd1be
      metricId: a45618a2-0154-4467-94f5-c7b001c63eee
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 5500
      incident:  
    - entityId: 31192d84-50cb-4296-873e-3ee25f3e3cb0
      metricId: 756fa555-9689-4a51-9cd1-6ae7b452141f
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
      incident:  
    - entityId: be7a3360-245d-4131-a2f3-e48d246cd1be
      metricId: 101e4f39-e32e-454f-9ad2-6066c7063046
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: Average
      min: 0
      max: 1000
      incident:  
    - entityId: be7a3360-245d-4131-a2f3-e48d246cd1be
      metricId: 3e83d974-d038-499b-81ae-116493cc1a9d
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99
      min: 0
      max: 4500
      incident:  
    - entityId: be7a3360-245d-4131-a2f3-e48d246cd1be
      metricId: 40911cd3-3a2d-4ce2-89d3-2853bdb4a580
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 5000
    - entityId: be7a3360-245d-4131-a2f3-e48d246cd1be
      metricId: 657850df-3ec1-4137-b421-31d6a6f34207
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: 75a1c89f-e3a1-4894-bac0-100f741f01d6
      metricId: 8bb80517-28f3-420b-9072-74320be359f7
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: 4df32df7-4c31-41ce-b661-e9d7c530c2f7
      metricId: 5ea6fb84-d1e3-4b21-a360-d4b2f91e16a3
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: TPM
      legendName: TPM
      min: 0
      max: 250
      incident:  
    - entityId: 31192d84-50cb-4296-873e-3ee25f3e3cb0
      metricId: 49394130-fe6c-4d53-9bff-80b15af30859
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
    - entityId: 31192d84-50cb-4296-873e-3ee25f3e3cb0
      metricId: 9a33652c-58f0-4095-aea0-7609725bce79
      parentEntityId: 25cfb111-8f2d-463c-9af6-a1a759181a87
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: UserException
      min: 0
      max: 50
      incident:  
