source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 1d23be80-a24a-4de8-83f7-64847148cd7c
      metricId: 04eda833-f944-4a93-8c22-77f07985e6ba
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99
      min: 0
      max: 4000
      incident:  
    - entityId: 1d23be80-a24a-4de8-83f7-64847148cd7c
      metricId: 372c925c-bd41-42e3-a52b-09160933bc11
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 4500
      incident:  
    - entityId: 1d23be80-a24a-4de8-83f7-64847148cd7c
      metricId: 5df26fbd-4ab5-4f38-ab04-5f31ce904016
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p95
      min: 0
      max: 2500
      incident:  
    - entityId: 1d23be80-a24a-4de8-83f7-64847148cd7c
      metricId: f08a8721-bc00-42ad-9d8c-57ff863a1876
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 4000
    - entityId: 1d23be80-a24a-4de8-83f7-64847148cd7c
      metricId: f5daaa30-228f-4edd-93c1-e5d96405896e
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Performance
      legendName: Average
      min: 0
      max: 1200
      incident:  
    - entityId: 97058851-4cd9-464c-8430-0ed12a589a9a
      metricId: d599a357-784d-418d-bcfc-bd076eecd9d7
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: TPM
      legendName: TPM
      min: 0
      max: 400
      incident:  
    - entityId: e04c9637-6f4d-4d0c-a60c-cef5dca76c28
      metricId: 3921da58-79d4-4d9f-ae5c-f300d7d01157
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: e882dd1c-af8a-4d55-914d-d1394060cfd1
      metricId: 044249a7-3113-474d-a79d-2d6272121dbb
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: BusinessException
      min: 0
      max: 40
      incident:  
    - entityId: e882dd1c-af8a-4d55-914d-d1394060cfd1
      metricId: 35108d1c-17b3-415e-bf6b-2aa1a9687900
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: e882dd1c-af8a-4d55-914d-d1394060cfd1
      metricId: 747a53ae-15bd-4f26-b9b2-4b44803710f6
      parentEntityId: cf4019bd-b699-4a04-a86f-fb1dcb9c2d3e
      containerName: OTP Delivery - POD
      graphName: Error
      legendName: UserException
      min: 0
      max: 50
      incident:  
