source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: f71fecee-b294-457d-ad4c-cd9496314550
      metricId: c6129f2a-21a4-40dd-ab41-0b0fcb9379a9
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.99
      incident:  
    - entityId: f71fecee-b294-457d-ad4c-cd9496314550
      metricId: df914130-37fd-49d2-8b0b-46d2784e9f5f
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Performance
      legendName: p99.9
    - entityId: f71fecee-b294-457d-ad4c-cd9496314550
      metricId: 38c16853-0116-4dda-ba49-410210330845
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Performance
      legendName: Average
      incident:  
    - entityId: f71fecee-b294-457d-ad4c-cd9496314550
      metricId: 697e8834-0723-41eb-9d41-958aa6873b2e
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Performance
      legendName: p95
      incident:  
    - entityId: c32a5924-04f0-4aac-89fd-c3fcc5042282
      metricId: f9a480e0-9b85-4f76-a7a3-0e1341f9adf1
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 250
    - entityId: ef254e4a-8d77-4f75-80a0-ce1cc26f6db3
      metricId: cb7ef0d5-4fa6-45fb-9dac-9ee27db2e929
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Error
      legendName: Failure
    - entityId: a9597060-efca-45e5-9d62-8c3b254556a2
      metricId: 09adb4c1-d969-4f83-ae97-aeb10f2b83f2
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Availability
      legendName: Availability
    - entityId: f71fecee-b294-457d-ad4c-cd9496314550
      metricId: 63b47a24-e449-45f3-a405-050085e84894
      parentEntityId: 793b8427-7e00-4843-9a83-f80d781f0c14
      containerName: Lockout DB
      graphName: Performance
      legendName: p99
      incident:  
