source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 71cbd118-5da4-4f6e-bb61-17450f729250
      metricId: 92454baa-5769-4180-84bd-558eabd4f495
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Performance
      legendName: Average
      min: 0
      max: 1000
      incident:  
    - entityId: 71cbd118-5da4-4f6e-bb61-17450f729250
      metricId: 793e77dc-e61c-40cb-a13c-2ac79ee59e32
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Performance
      legendName: p99
      min: 0
      max: 4000
      incident:  
    - entityId: 31609e1a-f2f6-41cf-b9c3-4304883b3b97
      metricId: ad58e9ce-9339-458c-9a7c-0aad043b3e98
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: TPM
      legendName: TPM
      min: 0
      max: 800
      incident:  
    - entityId: a12b03a9-ee23-4003-8ee3-68e534ad899c
      metricId: e2dd766c-6b2b-4ea5-be9e-03604c9a440f
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
    - entityId: 419c2fc9-9ea8-4099-b895-2a10fcf23fa5
      metricId: 138b1c4f-43d6-4798-ac6c-837fec3cf2d8
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 71cbd118-5da4-4f6e-bb61-17450f729250
      metricId: a844edcc-f964-4da5-948e-c216dd39ce9e
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: 71cbd118-5da4-4f6e-bb61-17450f729250
      metricId: 08aa8bca-5885-4da0-a58a-84122bcac751
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 4000
    - entityId: a12b03a9-ee23-4003-8ee3-68e534ad899c
      metricId: 7886a1f1-184a-4f3a-b19b-dd7d59b0ed7a
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Error
      legendName: UserException
      min: 0
      max: 20
      incident:  
    - entityId: a12b03a9-ee23-4003-8ee3-68e534ad899c
      metricId: 583661ad-98a1-4707-b6f7-776917b5ed59
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: 71cbd118-5da4-4f6e-bb61-17450f729250
      metricId: 1c64d3b6-d3b5-4b44-b636-b1bf9117d5c3
      parentEntityId: 7ab3289e-3f84-457d-971d-f0fd1b6899c3
      containerName: Verification Services
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 4000
      incident:  
