source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: c1ffdf03-5168-4695-b11c-679996accc7a
      metricId: 559af253-9c01-4041-a2ca-fa1201e7ecba
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Performance
      legendName: Average
      min: 0
      max: 150
      incident:  
    - entityId: c1ffdf03-5168-4695-b11c-679996accc7a
      metricId: 31fd5c77-df43-4b47-8716-396d64cee5f1
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1200
    - entityId: 9a3d5bad-6f30-4ff6-929a-4c9bf31c1185
      metricId: 5ed423ad-8c28-475c-85e1-75625f323393
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Error
      legendName: Exception
      min: 0
      incident:  
    - entityId: 52ff1298-4859-49b1-9033-8ab3708a0c1f
      metricId: c2ee35aa-b6ab-47be-8f31-21161929bee1
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: TPM
      legendName: TPM
      min: 0
      max: 250
      incident:  
    - entityId: c1ffdf03-5168-4695-b11c-679996accc7a
      metricId: 1a4a1841-433e-43f3-901d-6078b0da73c0
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Performance
      legendName: p99
      min: 0
      max: 1200
      incident:  
    - entityId: c1ffdf03-5168-4695-b11c-679996accc7a
      metricId: 2c48903a-82dc-4d67-b3f9-d68ada1511c0
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1200
      incident:  
    - entityId: c1ffdf03-5168-4695-b11c-679996accc7a
      metricId: 9447aac7-dd6d-4534-8b4b-01d076ec872d
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Performance
      legendName: p95
      min: 0
      max: 500
      incident:  
    - entityId: 9a3d5bad-6f30-4ff6-929a-4c9bf31c1185
      metricId: 04a05e4b-063c-4725-895e-c7ac6cfa3b85
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Error
      legendName: Failure
      min: 0
      incident:  
    - entityId: 9a6e4c76-c6ba-4c8b-8a63-4bd39c41beca
      metricId: 30857627-81bd-417a-9052-a99d2da30b1f
      parentEntityId: 2bbc3bf4-b6e8-40ab-ae89-24f378b06339
      containerName: Raven Communications
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
