source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: e53ca4f8-2974-4152-895e-cb0d3887e8af
      metricId: b49dae0c-65fb-48ef-b94c-03eb38e6e794
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Performance
      legendName: p95
      min: 0
      max: 3000
      incident:  
    - entityId: e53ca4f8-2974-4152-895e-cb0d3887e8af
      metricId: bdf80448-b088-4d07-b174-dcddbc504195
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Performance
      legendName: Average
      min: 0
      max: 1200
      incident:  
    - entityId: e53ca4f8-2974-4152-895e-cb0d3887e8af
      metricId: c9efc0bf-3250-47b5-ac98-0a169e271bf9
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Performance
      legendName: p99
      min: 0
      max: 3000
      incident:  
    - entityId: 840fc304-225c-45fc-942a-c0ee0d0d44a3
      metricId: 798c569f-20e6-47f8-b23e-2b2fddebdb80
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: TPM
      legendName: TPM
      min: 50
      max: 600
      incident:  
    - entityId: 7454078b-401c-48d3-85ab-11ea3522a755
      metricId: 64e26308-72d0-4a02-9644-6b99b83b1992
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Error Rate
      legendName: UserException
      min: 0
      max: 100
      incident:  
    - entityId: 7454078b-401c-48d3-85ab-11ea3522a755
      metricId: 7b23fac5-5fd4-47ef-bc11-78ea5e7836c4
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Error Rate
      legendName: BusinessException
      min: 0
      max: 100
      incident:  
    - entityId: e53ca4f8-2974-4152-895e-cb0d3887e8af
      metricId: a9dbea79-2bf3-4caf-9c14-c94d0acf4ff7
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 4000
      incident:  
    - entityId: e53ca4f8-2974-4152-895e-cb0d3887e8af
      metricId: 4738d1d4-8357-4666-87a0-32ec3490031a
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 4000
    - entityId: 7454078b-401c-48d3-85ab-11ea3522a755
      metricId: e6325eb2-1e63-4a52-ab40-b58e05eabd4f
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Error Rate
      legendName: Failure
      min: 0
      max: 20
      incident:  
    - entityId: 458a8500-4c31-41c3-8016-4352ddb14d01
      metricId: 42848d35-3202-4643-a744-4e521fa3f882
      parentEntityId: 6cc0460a-3970-4167-bcab-f7dc19676654
      containerName: POD
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
