source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: ba4f2f90-1d0e-41df-8427-723565b863b0
      metricId: d445e0f9-f0cd-4cc9-bd12-0630c180021f
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Performance
      legendName: p99
      min: 0
      max: 900
      incident:  
    - entityId: 15c4d569-623a-423e-980d-b9e6fdb6e675
      metricId: 6a1b34de-0f21-4024-b9a9-c1a711e78644
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Error
      legendName: Exception
      min: 0
      max: 20
      incident:  
    - entityId: ba4f2f90-1d0e-41df-8427-723565b863b0
      metricId: 4c1ce17e-ffcc-4a42-b2bd-1163b4efe626
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Performance
      legendName: p95
      min: 0
      max: 700
      incident:  
    - entityId: ba4f2f90-1d0e-41df-8427-723565b863b0
      metricId: bada575e-b476-4b92-aa39-53c513280af2
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Performance
      legendName: Average
      min: 0
      max: 130
      incident:  
    - entityId: ba4f2f90-1d0e-41df-8427-723565b863b0
      metricId: b1eb8547-ddba-40e3-86a6-3f30a12c98c7
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2000
      incident:  
    - entityId: 15c4d569-623a-423e-980d-b9e6fdb6e675
      metricId: 71bf1a93-eb0f-4f0a-91a4-26c0a6f215b4
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: 815edacd-5fed-441d-a8ec-dedf0950dcab
      metricId: 9fb0cc53-eff5-4dae-b3ee-088feb1f98c8
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: TPM
      legendName: TPM
      min: 0
      max: 400
      incident:  
    - entityId: 0380b244-f545-4c52-a1ae-10f303ac71b1
      metricId: 4c00291a-0661-494c-9eea-47145c91b630
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: ba4f2f90-1d0e-41df-8427-723565b863b0
      metricId: e93af470-466d-45ec-af73-f2215508c8d0
      parentEntityId: ad9669c1-f12e-433a-9073-08b59622d62b
      containerName: Push AuthN - PUSH Delivery
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
