source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: a8b2f1b1-1126-496d-aa50-2c28dce6c7ff
      metricId: b07c090d-e9ed-47a2-ab55-007789d79f67
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Performance
      legendName: Average
      min: 0
      max: 350
      incident:  
    - entityId: a8b2f1b1-1126-496d-aa50-2c28dce6c7ff
      metricId: f1a5f5e2-bc46-492a-bf54-d66365064eb6
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2200
    - entityId: a8b2f1b1-1126-496d-aa50-2c28dce6c7ff
      metricId: fe6d4941-8b7c-4542-9242-e5589f9a241d
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Performance
      legendName: p95
      min: 0
      max: 800
      incident:  
    - entityId: 41cf2ab5-c86a-43e1-b61b-ba188c1782a1
      metricId: b4c38e14-e0b2-4eb2-9c91-87e4e2ef7f5f
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: TPM
      legendName: TPM
      min: 0
      max: 120
      incident:  
    - entityId: 8b6bba14-92f0-467c-b976-26a2815f6065
      metricId: 4dd6ed69-11bb-4d1a-ad5b-5bd78ab9f68b
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Error
      legendName: Failure
      min: 0
      max: 10
      incident:  
    - entityId: f1e1a3eb-33c4-46e3-a86e-cbdec0657595
      metricId: 7ced4f2b-3f14-4979-a570-ab26db2c1a3d
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: a8b2f1b1-1126-496d-aa50-2c28dce6c7ff
      metricId: 4b4ab8bd-0d09-425b-9c0c-7e683e2652e0
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2500
      incident:  
    - entityId: a8b2f1b1-1126-496d-aa50-2c28dce6c7ff
      metricId: 9312bf40-8581-473d-b4d2-7be4490cc5bd
      parentEntityId: 0073ec4b-2c4c-4444-8b22-eab680d4b446
      containerName: CAS
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
      incident:  
