source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 64bf8521-8279-4549-a638-19fc08464642
      metricId: f1afe523-9d28-4182-8d25-a3011cfc0c80
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Performance
      legendName: p99
      incident:  
    - entityId: 90049854-e027-47f4-baa8-27477030fd0f
      metricId: 332420ba-17b1-4545-9ff6-b8a986877b02
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: TPM
      legendName: TPM
      min: 0
      max: 300
      incident:  
    - entityId: 9c726284-e96b-4c10-909a-14528ef067bf
      metricId: 57762829-91b7-41f8-9725-5e8848e8eae3
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Error
      legendName: Failure
      min: 0
      max: 30
      incident:  
    - entityId: de26fa21-aec3-45df-81e4-d935a0831e1b
      metricId: 52790e50-e2e0-44a4-8451-e03733451895
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Availability
      legendName: Availability
      min: 95
      max: 100
      incident: sev2
    - entityId: 64bf8521-8279-4549-a638-19fc08464642
      metricId: 1a639d58-bc65-4c74-ba41-4f35527f97ca
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Performance
      legendName: Average
      min: 0
      max: 2000
      incident:  
    - entityId: 64bf8521-8279-4549-a638-19fc08464642
      metricId: 9267ccb8-6dc1-4b8e-abd4-c9cf4c39122a
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Performance
      legendName: p95
      incident:  
    - entityId: 64bf8521-8279-4549-a638-19fc08464642
      metricId: c3fd01c1-087c-4f52-9b13-910a268aa1f2
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Performance
      legendName: p99.9
    - entityId: 64bf8521-8279-4549-a638-19fc08464642
      metricId: d84405fd-6699-4af0-91d0-7012d40afd26
      parentEntityId: ec8c654d-0565-41b9-9319-35f15f417e00
      containerName: Verf - SMS Dispatcher
      graphName: Performance
      legendName: p99.99
      incident:  
