source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: e4adb3f0-a276-4b18-8e23-f1b31b1c6e37
      metricId: 65e72a39-9142-44fc-bcad-5d773718bad1
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Performance
      legendName: p99
      min: 0
      max: 500
      incident:  
    - entityId: 697ec582-6aa9-4e54-bc45-727ba4178fa2
      metricId: d3dc5c16-cd25-436a-bb28-3c509c9f3e60
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Error
      legendName: Count
      min: 0
      max: 20
      incident: sev2
    - entityId: 36d955ad-29b8-41bd-9095-35f28b58ffd6
      metricId: 46436880-4d38-43e7-bf33-d26f69adcb34
      parentEntityId: b90c97f8-267c-4b96-8061-8e90318d4a0d
      containerName: Biometric Login Availability Dependencies
      graphName: Product Registry
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: 9d3bca95-6dc9-4f42-b963-724488be8119
      metricId: d3dc5c16-cd25-436a-bb28-3c509c9f3e60
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: TPM
      legendName: Count
      min: 0
      max: 300
      incident:  
    - entityId: e4adb3f0-a276-4b18-8e23-f1b31b1c6e37
      metricId: 5c681bda-f201-43a1-be24-cdfd92a1aed6
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 500
      incident:  
    - entityId: e4adb3f0-a276-4b18-8e23-f1b31b1c6e37
      metricId: 67653273-bfb4-4ae7-a8e2-e11ee0742675
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Performance
      legendName: p95
      min: 0
      max: 250
      incident:  
    - entityId: e4adb3f0-a276-4b18-8e23-f1b31b1c6e37
      metricId: 577af147-0aba-4071-b926-3c9ab2d16b15
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Performance
      legendName: Average
      min: 0
      max: 80
      incident:  
    - entityId: e4adb3f0-a276-4b18-8e23-f1b31b1c6e37
      metricId: 74556b5a-9f51-44c4-813d-f4aa714cb347
      parentEntityId: eb8673ae-d642-4f73-868b-d9215eb0b147
      containerName: ProductRegistry Availability Golden Signals
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 500
