source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: a116ea34-f284-49bf-b10b-55919b1723d0
      metricId: e2a87bbc-abb8-4534-ad7b-24c51ee1e91e
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
    - entityId: 09b8a86b-0718-4db8-bc1e-5b70d1cb60e3
      metricId: 61160239-1a7c-46ca-89ae-ca96522d07ca
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 800
      incident:  
    - entityId: 82a29cd4-77bb-4f65-a31b-d23d5b10db62
      metricId: db2d9380-4e87-4fc9-9df8-ab69f7961801
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 500
      max: 2000
      incident:  
    - entityId: deb74dd8-d25d-4e38-ac44-e1a62fc58fc6
      metricId: ba34914f-2388-470c-8aa2-b991f7b2c2b1
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Error
      legendName: BusinessException
      min: 0
      incident:  
    - entityId: deb74dd8-d25d-4e38-ac44-e1a62fc58fc6
      metricId: d35ac5cc-b584-4532-a614-ef5701536c7c
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Error
      legendName: UserException
      min: 0
      incident:  
    - entityId: 09b8a86b-0718-4db8-bc1e-5b70d1cb60e3
      metricId: def31c96-967a-459f-b95b-82fe55f2bebd
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: 09b8a86b-0718-4db8-bc1e-5b70d1cb60e3
      metricId: 03d96a21-2215-4c33-8810-fac4171bc335
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 800
      incident:  
    - entityId: 09b8a86b-0718-4db8-bc1e-5b70d1cb60e3
      metricId: d606f7ec-bc73-4b9a-987e-7352353cc23d
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 350
      incident:  
    - entityId: 09b8a86b-0718-4db8-bc1e-5b70d1cb60e3
      metricId: 571956ff-0410-4ea8-91d0-d35237f4ee06
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1200
    - entityId: deb74dd8-d25d-4e38-ac44-e1a62fc58fc6
      metricId: 30a9ccbf-8ee5-477f-a359-e30c20534adc
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
