source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: aac225e1-1af9-46ac-ae37-f8fc105e7e05
      metricId: 243962b7-e95c-4701-895b-6b37fc84a3f4
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Performance
      legendName: p95
      min: 0
      max: 1000
      incident:  
    - entityId: aac225e1-1af9-46ac-ae37-f8fc105e7e05
      metricId: 7220a050-3258-485b-8884-8ff24d949ad6
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1500
      incident:  
    - entityId: be4c9e9c-70c4-446c-943b-e06e9a108344
      metricId: 2d149d36-d5c9-402c-be8d-5c131b406ebc
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Error
      legendName: BusinessException
      min: 0
      max: 100
      incident:  
    - entityId: be4c9e9c-70c4-446c-943b-e06e9a108344
      metricId: 2b98e9ab-a1a7-4570-a580-6227868159b2
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
    - entityId: be4c9e9c-70c4-446c-943b-e06e9a108344
      metricId: c552e6b0-69d7-48f5-8b4c-dac69cba139f
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Error
      legendName: UserException
      min: 0
      max: 25
      incident:  
    - entityId: 6833c868-6b12-4a70-a215-c76c7d358180
      metricId: a7f62288-38c5-47c9-aab1-32c66708b313
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: aac225e1-1af9-46ac-ae37-f8fc105e7e05
      metricId: 74b1dabc-7a38-4407-89de-b5ca31a21397
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: aac225e1-1af9-46ac-ae37-f8fc105e7e05
      metricId: a800a11a-35c7-4f13-8e86-59436c77f4dc
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
      incident:  
    - entityId: aac225e1-1af9-46ac-ae37-f8fc105e7e05
      metricId: eb06800a-a520-4e1e-89bf-2f69d133c95b
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: Performance
      legendName: Average
      min: 0
      max: 500
      incident:  
    - entityId: 2367e8be-99c3-4273-a0c3-15592486b97b
      metricId: 837de82b-20f3-44da-bedc-dbd06ce73201
      parentEntityId: c546cd21-63c3-4bc9-a8e1-e134300b189b
      containerName: Verification Services
      graphName: TPM
      legendName: TPM
      min: 500
      max: 2000
      incident:  
