source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 865c6899-1b84-4c9e-a3dc-899ff6c992a2
      metricId: ca55757a-f55d-4445-99dd-1aa815e73cde
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 3000
    - entityId: 865c6899-1b84-4c9e-a3dc-899ff6c992a2
      metricId: e58fbc00-44f4-4f36-bb29-f6e5bf8980e4
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
    - entityId: a0d0b323-adc7-4e6b-b98d-4ba97f4d1fdc
      metricId: bbf09178-eb8e-4c17-8950-b58ae6cf9144
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: TPM
      legendName: TPM
      min: 0
      max: 25
    - entityId: 0bb00018-229c-4561-988c-b05737182c24
      metricId: 2aae5ef4-f438-4c51-b788-1724572136b0
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: 7ea420a6-d64d-44f4-bb09-2393d76a691f
      metricId: 0ca1ac0e-47b9-4784-8880-8c468d53b870
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Availability
      legendName: Availability
      min: 94
      max: 100
      incident: sev2
    - entityId: 865c6899-1b84-4c9e-a3dc-899ff6c992a2
      metricId: 0b4b213b-dbb0-4060-b728-4c4d60fad52b
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Performance
      legendName: Average
      min: 0
      max: 350
    - entityId: 865c6899-1b84-4c9e-a3dc-899ff6c992a2
      metricId: 4411aff6-f938-4518-8882-ff6ce60a3c6a
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: 865c6899-1b84-4c9e-a3dc-899ff6c992a2
      metricId: 7ac970f3-6c26-4d3a-b519-095135e1c462
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: CAS
      graphName: Performance
      legendName: p95
      min: 0
      max: 750
