source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 11dfab2f-12c7-4115-a021-17988930fa29
      metricId: 11b6369a-c733-4c46-b812-07cd90edc3fc
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Performance
      legendName: Average
      min: 0
      max: 500
    - entityId: 11dfab2f-12c7-4115-a021-17988930fa29
      metricId: 22c2f968-1504-4ad8-b008-b90ebe8c19cf
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2500
    - entityId: 11dfab2f-12c7-4115-a021-17988930fa29
      metricId: 77e19456-a60d-40a9-918e-6d2a128b23be
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: 11dfab2f-12c7-4115-a021-17988930fa29
      metricId: 7a5a938f-1f10-47ff-a33c-ec52679fb2cf
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Performance
      legendName: p95
      min: 0
      max: 750
    - entityId: 11dfab2f-12c7-4115-a021-17988930fa29
      metricId: c405399f-742e-4601-b5ac-5669d8020624
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Performance
      legendName: p99
      min: 0
      max: 1500
    - entityId: b020f456-cb76-43d3-8d91-3d25a75884ca
      metricId: f588e064-c43c-42f1-b286-22bcbb4a2ba9
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: TPM
      legendName: TPM
      min: 50
      max: 750
    - entityId: e50ef607-5b9b-4930-951e-abd9e739925f
      metricId: f94318b2-e8df-4cef-bdac-0f2dd0d93bc9
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Error
      legendName: Failure
      min: 0
      max: 25
    - entityId: db71c2ec-0591-47f9-a2ef-d93de1b5bfea
      metricId: babced85-09cc-45f0-921e-5d12f3463000
      parentEntityId: 962e30f1-b87e-49df-b519-5007b9bd3d0b
      containerName: MemberService
      graphName: Availability
      legendName: Availability
      min: 98
      max: 100
      incident: sev2
