source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 6491972c-1986-4851-b200-bd153afcb08b
      metricId: ed62c0e2-4880-47ac-a4b2-5ce136a066c8
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Performance
      legendName: p99
      min: 0
      max: 150
      incident:  
    - entityId: 6491972c-1986-4851-b200-bd153afcb08b
      metricId: 27c46fe4-efd4-47a3-a8b3-19945e124485
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 25
    - entityId: 2ef75db8-abc3-4ade-8e22-694b274e8410
      metricId: fd0d477e-a3a6-437b-aeb8-820befb89d6b
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Error
      legendName: Failure
      min: 0
      max: 5
      incident: sev2
    - entityId: 21136ad1-c8d0-4f6b-9e2b-d6c230faba85
      metricId: ca9984e5-b9a4-493c-918d-17dd0de4147e
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Availability
      legendName: Availability
      min: 99.9
      max: 100
      incident: sev2
    - entityId: 6491972c-1986-4851-b200-bd153afcb08b
      metricId: bb0729fc-3e5c-4d78-834c-4de203cc6d91
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: 6491972c-1986-4851-b200-bd153afcb08b
      metricId: 68fbddee-c86f-4955-879b-9a82c55137b1
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Performance
      legendName: p95
      min: 0
      max: 15
      incident:  
    - entityId: 2ef75db8-abc3-4ade-8e22-694b274e8410
      metricId: 50bc75d1-705a-4ee0-87f5-c36d01963922
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Error
      legendName: Exception
      max: 2
      incident: sev2
    - entityId: d9a35b25-a5a3-4f2a-a73b-943dd5f4c501
      metricId: d9806d56-06ed-40c1-944b-7c1f3839cafc
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: TPM
      legendName: TPM
      max: 5
      incident:  
    - entityId: 6491972c-1986-4851-b200-bd153afcb08b
      metricId: ea96821c-9a1e-4953-aead-3da0c9ab6133
      parentEntityId: 08afbfe9-62c6-47ce-8dca-c1a4e2f9c6a3
      containerName: TOTP service - Validate code
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 50
      incident:  
