source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: bd16d587-4cec-4c82-812b-68ce8a37184f
      metricId: 3e6bf951-f0d3-48bb-869d-d1ea74dcf4eb
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 1000
      incident:  
    - entityId: bd16d587-4cec-4c82-812b-68ce8a37184f
      metricId: 835f7ca2-c408-4731-836a-04b3c7a9dc50
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Performance
      legendName: Average
      min: 0
      max: 100
      incident:  
    - entityId: 8e831b01-afd3-4ae1-8f69-968198acb6fa
      metricId: 994e21e5-dbc5-4488-a3da-a177bb50db34
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: TPM
      legendName: TPM
      min: 200
      max: 3000
      incident:  
    - entityId: fde75c62-eda5-4969-9a0e-9695107d0541
      metricId: 0d42d531-c44c-4258-a3c1-3617227af55f
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Error
      legendName: Failure
      min: 0
      max: 50
    - entityId: d48ace04-a372-47c4-a817-f337cd63b853
      metricId: 8d2aec87-63ca-495d-afde-50977b62a3b5
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Availability
      legendName: Availability
      min: 96
      max: 100
      incident: sev2
    - entityId: bd16d587-4cec-4c82-812b-68ce8a37184f
      metricId: b70b822a-a8fd-4240-9dd8-ea7746f1b300
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Performance
      legendName: p99
      min: 0
      max: 700
      incident:  
    - entityId: bd16d587-4cec-4c82-812b-68ce8a37184f
      metricId: 06f56536-8f60-455b-baac-eb3752f21a53
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Performance
      legendName: p95
      min: 0
      max: 400
      incident:  
    - entityId: bd16d587-4cec-4c82-812b-68ce8a37184f
      metricId: 4a607e37-5be9-449c-bb17-24f1dbcdc359
      parentEntityId: c8df7f65-1f0e-4628-bc9b-887885c4e6a1
      containerName: Tokenizer
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 1200
