source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: f8d4a4fb-0d40-41ab-b31c-ecba2f6f21a7
      metricId: ccf1523a-b43d-45f4-9e5d-ffe87755f9bd
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Performance
      legendName: p95
      min: 0
      max: 750
      incident:  
    - entityId: f8d4a4fb-0d40-41ab-b31c-ecba2f6f21a7
      metricId: 3bbe1e7c-9a70-425d-998d-1caffa5710ec
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
      incident:  
    - entityId: f8d4a4fb-0d40-41ab-b31c-ecba2f6f21a7
      metricId: 61b12018-281c-4cab-a4d9-46d74826cdf9
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Performance
      legendName: Average
      min: 0
      max: 300
      incident:  
    - entityId: cc39d9fe-0099-4a6b-bad6-f0c7f8c7403a
      metricId: 8a6f9058-0f86-48b1-a23d-e52d7b7e7eae
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Error
      legendName: UserException
      min: 0
      max: 40
      incident:  
    - entityId: 29467b55-cb54-45df-91f0-6588cf3dde22
      metricId: c013cafc-9391-4096-91ce-8cd553e42fb1
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
    - entityId: f8d4a4fb-0d40-41ab-b31c-ecba2f6f21a7
      metricId: bdbd88c0-a591-489e-9c54-a916bfafb449
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2500
    - entityId: f8d4a4fb-0d40-41ab-b31c-ecba2f6f21a7
      metricId: 921f6c4d-6b98-4639-9bac-e56b506a1965
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 2500
      incident:  
    - entityId: 588f5912-13be-417e-b4b3-d3577c05fd3c
      metricId: 37f17ec4-e9a3-478d-8d40-2ea042d1b759
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: TPM
      legendName: TPM
      min: 0
      max: 350
      incident:  
    - entityId: cc39d9fe-0099-4a6b-bad6-f0c7f8c7403a
      metricId: ffb72219-f2ff-47c9-bac4-82b26f27351f
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Error
      legendName: BusinessException
      min: 0
      max: 40
      incident:  
    - entityId: cc39d9fe-0099-4a6b-bad6-f0c7f8c7403a
      metricId: 94c1ef3f-478e-4eb4-b9c8-71eb043898c6
      parentEntityId: 6b14bd7f-af09-4b8a-8490-3852cd52cda0
      containerName: Verf
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
