source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 2d776df7-b1a6-4adc-8ab7-cb9eee90b184
      metricId: 2bc00d26-4060-4b22-b750-99a0b42a9866
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: TPM
      legendName: Count
      min: 0
      max: 8000
      incident:  
    - entityId: c764a657-1d86-4278-b125-8eed7df25434
      metricId: 1abdf544-db16-453a-b02e-d0bf89189fea
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99
      min: 0
      max: 500
      incident:  
    - entityId: c764a657-1d86-4278-b125-8eed7df25434
      metricId: 23a50f4e-2b1e-4b7e-a4ff-76c02b55ca5a
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 500
    - entityId: c764a657-1d86-4278-b125-8eed7df25434
      metricId: b103d49a-5aeb-40a9-987c-7f41969ba915
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: Average
      min: 0
      max: 40
      incident:  
    - entityId: c764a657-1d86-4278-b125-8eed7df25434
      metricId: b49e8a30-21aa-4c20-9b16-8aa00de9ad87
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p95
      min: 0
      max: 100
      incident:  
    - entityId: c764a657-1d86-4278-b125-8eed7df25434
      metricId: c9835063-43bb-4b57-aab7-6723ce5ef63c
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 500
      incident:  
    - entityId: 97188218-70c6-4717-92a5-723c8f735422
      metricId: 2bc00d26-4060-4b22-b750-99a0b42a9866
      parentEntityId: 483bbb50-01c8-4e0b-b9bd-be041cd55b08
      containerName: MFADB Availability Golden Signals
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
      incident: sev2
    - entityId: 435120d5-3b0e-4d00-9e83-7e6fdc5b1ef4
      metricId: 77a11f78-7572-403b-a2a4-f6fe08067148
      parentEntityId: 74e6a339-3537-4fe5-8b9a-0ce884502bc2
      containerName: CBIS Availability Dependencies
      graphName: MFA DB
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
