source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: 9b38ba4c-9f83-4128-b8b2-04fe5cb8e54a
      metricId: 498def99-22d6-4489-bd78-64868134755b
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Error
      legendName: Failure
      min: 0
      max: 20
    - entityId: d753aade-ab82-4ff4-b5a8-90ee78ef9fe6
      metricId: ca8474b2-e502-4aad-8110-c3668e325f02
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: TPM
      legendName: TPM
      min: 0
      max: 400
      incident:  
    - entityId: 599f87c5-ff6c-4340-a3b3-88858cb5fd92
      metricId: c542ac01-f2eb-467c-9443-2802bd4cbfac
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Performance
      legendName: p99
      min: 0
      max: 2000
      incident:  
    - entityId: 599f87c5-ff6c-4340-a3b3-88858cb5fd92
      metricId: 1c636a0f-6bb1-4b2d-8bec-5cc44b775b55
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 2000
    - entityId: 599f87c5-ff6c-4340-a3b3-88858cb5fd92
      metricId: 76dc3a04-bde8-4e5f-97b5-2ba6042b4705
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Performance
      legendName: p95
      min: 0
      max: 1500
      incident:  
    - entityId: 599f87c5-ff6c-4340-a3b3-88858cb5fd92
      metricId: 93dfa80d-c652-4ac5-93ce-ef8575fc6c43
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 3000
      incident:  
    - entityId: 599f87c5-ff6c-4340-a3b3-88858cb5fd92
      metricId: d6c3d2f0-cf16-4a6e-a50f-e65136b7d193
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Performance
      legendName: Average
      min: 0
      max: 800
      incident:  
    - entityId: 9b38ba4c-9f83-4128-b8b2-04fe5cb8e54a
      metricId: f9c767aa-ee5f-4abb-b711-2c06f64c635c
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Error
      legendName: Exception
      min: 0
      max: 40
      incident:  
    - entityId: 5b7ce260-d3df-4c45-985f-c06ce362dc2a
      metricId: 31fb3773-f1ac-4493-86ef-805cce4d3611
      parentEntityId: b06942b0-922a-4e3c-861f-860676679fc3
      containerName: OneAuth - OTP Delivery
      graphName: Availability
      legendName: Availability
      min: 99
      max: 100
      incident: sev2
