source:
  defaultConfig:
    emailConfigName: ""
    slackConfigName: ""
    incidentSevTwoConfigName: SolveInsights-OneIdentity-Sev2
    incidentSevThreeConfigName: SolveInsights-OneIdentity-Sev3
    incidentSevFourConfigName: SolveInsights-OneIdentity-Sev4
    incident:
      severity: Sev4
      enabled: false
  entity:
    name: Enterprise Login
    id: b9dad97a-63d7-4cc2-91a5-cadba667cfa8
    ignore:
      entityIds: []
    whitelist:
      entityIds: []
    metricThresholds:
    - entityId: c49b5a89-d9dc-48b9-a8d4-561d7317481a
      metricId: a588fd03-297a-4904-b433-2d601c44f02e
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: TPM
      legendName: TPM
      min: 0
      max: 250
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: 82ff9e11-76fc-452c-8af8-e9db12802ece
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_S
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: c6710790-ed90-4db9-b17b-e75ce1ba713d
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_S
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: df7d4e67-3b1f-4886-b023-98115d7c4b1e
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_P
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: d6336c89-0082-4ff2-a74f-001aca4736f9
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_T
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: df66c0c3-9a18-44b9-890e-b62a3f778f0a
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_P
      min: 0
      max: 15
      incident:  
    - entityId: 0f1b4a20-4369-43a1-836d-b79c179f8189
      metricId: 8f5c5303-2103-4510-ab48-23d4ec699db6
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Availability
      legendName: Availability
      min: 97
      max: 100
      incident: sev2
    - entityId: c3afb5c2-f92f-4c0f-af5a-5f7d8eb73e0f
      metricId: 92bdb8e2-f7b1-4511-807b-30228fc48261
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Performance
      legendName: p99.9
      min: 0
      max: 150
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: 194ed262-2b66-4652-b8fb-4c49788684c7
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_S
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: f7b7c04a-0fe0-415c-86f0-06eb0b4491de
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionSuccess_CardsDB_T
      min: 0
      max: 15
    - entityId: c3afb5c2-f92f-4c0f-af5a-5f7d8eb73e0f
      metricId: 3f80a3c6-0082-4a4d-9c5e-527ce8c7bceb
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Performance
      legendName: p99.99
      min: 0
      max: 150
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: d5c1cfdb-c09e-41e1-827a-8387108cd8cd
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_P
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: 2cda45d4-e570-40d1-b640-78b26d152447
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzSuccess_CardsDB_T
      min: 0
      max: 15
    - entityId: c3afb5c2-f92f-4c0f-af5a-5f7d8eb73e0f
      metricId: 52891762-c532-446f-a9ff-13fbfb3e59fc
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Performance
      legendName: Average
      min: 0
      max: 20
    - entityId: c3afb5c2-f92f-4c0f-af5a-5f7d8eb73e0f
      metricId: f913032a-cabc-4c11-a13d-6cf1ef604726
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Performance
      legendName: p99
      min: 0
      max: 150
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: b4f06ffc-bd4f-4907-8443-6737f5a96136
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: AzFailure_CardsDB_P
      min: 0
      max: 15
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: 0079f32b-61a8-4a55-8e87-c7127b4ac237
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_T
      min: 0
      max: 15
    - entityId: c3afb5c2-f92f-4c0f-af5a-5f7d8eb73e0f
      metricId: ce93d445-358f-48ed-a134-261caaff4fab
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Performance
      legendName: p95
      min: 0
      max: 20
    - entityId: deb33de0-1406-4460-a407-d54edd859cc0
      metricId: af37024b-af16-44f5-88e6-3c16afb4780e
      parentEntityId: a9efa542-7827-4707-a891-2318e4057e19
      containerName: Cards DB
      graphName: Error
      legendName: ConnectionFailure_CardsDB_S
      min: 0
      max: 15
